### ISSUE TITLE
Can't build the wfmash dependency

### ISSUE THREAD

**Issue by egoltsman** [pangenome/pggb#112]
After git-cloning the repo and attempting to run the de-novo graph generaton workflow,  the program fails to find wfmash which, indeed, I hadn't installed.   I tried building wfmash from the github repo, but gave up after a bunch of linker errors (
see https://github.com/ekg/wfmash/issues/87).  Would it be possible to bundle a wfmash static binary with the pggb release?

Thanks!

**Comment by AndreaGuarracino** [comment]
It should be a `gcc` version problem (https://github.com/ekg/wfmash/issues/87#issuecomment-871140854). Let us know!

**Comment by ekg** [comment]
What architecture are you targeting?

**Comment by egoltsman** [comment]
This is on x86_64-suse-linux.  I tried it with gcc 9.3.0 and higher - same pthreads issue.

**Comment by subwaystation** [comment]
@egoltsman Does the docker image work for you?

**Comment by ekg** [comment]
Could this be due to us trying to make a static binary, and the
corresponding libpthread.a not including the right set of functions?

**Comment by egoltsman** [comment]
> 
> 
> @egoltsman Does the docker image work for you?

Unfortunately, I can't use docker in my environment due to a security policy.

**Comment by subwaystation** [comment]
How about Bioconda or GUIX?

**Comment by egoltsman** [comment]
@subwaystation :   Sure, Conda would work.  I'm building this as part of the pggb package, but the link you sent refers to odgi, which, as I understand is about graph visualizations.  Can you comment?

**Comment by subwaystation** [comment]
I somehow confused things. Sorry @egoltsman. We don't have a Bioconda package of wfmash, yet.

Maybe it is time to do so :)

**Comment by AndreaGuarracino** [comment]
Hopefully, it will come soon https://github.com/bioconda/bioconda-recipes/pull/29772

**Comment by subwaystation** [comment]
@egoltsman It is on Bioconda https://anaconda.org/bioconda/wfmash. Does that solve your issue?

**Comment by egoltsman** [comment]
Thank you for the conda package.  Unfortunately, it's not liking my base environment which I just create from scratch.  If I'm reading this correctly, different components of wfmash require different versions of the same library (e.g. libgcc-ng) ?

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package _libgcc_mutex conflicts for:
python=3.9 -> libgcc-ng[version='>=7.5.0'] -> _libgcc_mutex[version='*|0.1',build=main]
wfmash -> libgcc-ng[version='>=9.3.0'] -> _libgcc_mutex[version='*|0.1',build=main]

Package libstdcxx-ng conflicts for:
wfmash -> jemalloc[version='>=5.2.1'] -> libstdcxx-ng[version='>=7.3.0']
wfmash -> libstdcxx-ng[version='>=9.3.0']

Package libgcc-ng conflicts for:
wfmash -> libgcc-ng[version='>=9.3.0']
wfmash -> jemalloc[version='>=5.2.1'] -> libgcc-ng[version='>=7.2.0|>=7.3.0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.26=0
  - feature:|@/linux-64::__glibc==2.26=0
  - python=3.9 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.26
```

**Comment by egoltsman** [comment]
p.s. I could try to get a docker container running, but since I need wfmash as a dependency for pggb, I'm afraid I don't know how to link the two if the former is containerized.

**Comment by subwaystation** [comment]
Hi @egoltsman 

That's a weird error.
I just did `conda create --name wfmash wfmash` followed by `conda activate wfmash` and it works as expected. 
Maybe you need to add `wfmash` to your environment first, then the other toolings? Or your base environment does not incorporate the most recent GCC toolchain of conda. They had some recent updates, that's maybe why you are still stuck with GCC v7.2 instead of GCC v9.3. Backwards compatibility might be tricky here.

We also have a docker image which contains all required pggb tools: https://github.com/pangenome/pggb#docker.

**Comment by egoltsman** [comment]
Ah, yes! I was indeed my conda that needed an update.  I was finally able to create the environment and pggb is running now. 
Thanks so much!
