### ISSUE TITLE
Behaviour of PGGB when resuming

### ISSUE THREAD

**Issue by brettChapman** [pangenome/pggb#119]
Hi

After PGGB completes, I'm intending to add spliced regions to my seqwish graph using ```vg rna``` and then adding it back in to resume from the smoothxg step to normalise the splice regions.

I was wondering, to resume, do I need to specify the same parameters again, or will PGGB read the yaml file to infer which parameters to resume with? So I could basically just run ```pggb -r -o output_folder```. Thanks.

**Comment by subwaystation** [comment]
Hi @brettChapman 

PGGB scans the given files in the `output_folder`. If a file is present, it won't be created again.
In order for this to work, please run your initial command line adding `--resume`.
Just replace the `seqwish` file with the new one. It must have the same name, or it won't work.

Best,
Simon

**Comment by subwaystation** [comment]
@brettChapman Are you happy with the current resume function?

**Comment by AndreaGuarracino** [comment]
`pggb` does not read the YAML file, but always uses command line parameters to create filenames and,  if `--resume` is specified, deduce which files not to create again. So you have to specify the whole original command line each time for resuming the run.

**Comment by ekg** [comment]
Note that you can also change parameters of later steps and resume based
off of earlier ones. For instance you can change the smoothxg parameters
without redoing the wfmash alignment so long as you don't change the wfmash
parameters.
