### ISSUE TITLE
Issue with the vcf file created using pggb graphs

### ISSUE THREAD

**Issue by GSgen** [pangenome/pggb#127]
Hello,

I have created `pggb` graph genome for a chromosome 
<img width="1221" alt="pggb" src="https://user-images.githubusercontent.com/88198051/127892891-9cdfe2cf-86fa-4e63-9980-b09b699e4363.png">
I made a dot plot of two samples (one with the extra piece and other not) using `mashmap` with the same percent identity and segment length as `pggb`
<img width="622" alt="dot plot" src="https://user-images.githubusercontent.com/88198051/127893131-cdac76a1-6b70-46f0-8dbc-0b191a10f7a4.png">
Then I made a vcf file using `vcf deconstruct` to locate the insertion but I am not able to find the insertion in the vcf file based on `pggb` graph. I am not able to attach the vcf file here. I can send the` vcf` file separately, if needed.

I `used` BLAST and it looks like there are repetitive sequences in this region (5000000-10000000). I will appreciate any help in figuring out the insertion in vcf file.

Thank you!

**Comment by ekg** [comment]
It looks like this variant should be detected. Is there a size limit on the snarls that go into the VG deconstruct output?

**Comment by subwaystation** [comment]
Any updates @GSgen ?
