### ISSUE TITLE
problem in running pggb with empty file

### ISSUE THREAD

**Issue by anna176577** [pangenome/pggb#129]
Hi All,

I am running `pggb` using:
`pggb -i input.fa -w 100000 -s 100000 -p 80 -a 100 -n 24 -k 8 -I 0.6 -R 0.2 -t 16 -v -L -o out `

It produces all the files but the `input.paf` file is empty. The `1-D` graph not not look correct and there is no `2-D` graph output. Thank you!

**Comment by AndreaGuarracino** [comment]
Hi @anna176577, it seems you are using a pretty old version of `pggb`, For example, the `-a` is not supported anymore (I've just updated the README, where that parameter was still mentioned).  Could you please update your installation, remove that parameter, and retry?

In case you still have problems, it could be useful to know what level of divergence you expect between the sequences in your dataset.

**Comment by anna176577** [comment]
Hi @AndreaGuarracino, I updated pggb version and used these parameters:
`pggb -i input.fa -s 100000 -p 80 -n 24 -k 8 -I 0.6 -R 0.2 -t 16 -v -o out`

It is running but taking much longer as it took with the previous version. I only see a` log` file and an `yml `file. The `paf `file is not made yet. Could you please suggest if there is something wrong with the parameters? Thank you!

**Comment by AndreaGuarracino** [comment]
Hi @anna176577, sorry for the delay, your run is probably over (hopefully). Nothing wrong, but the identity threshold is pretty low (`-p 80`), so you are exploring also regions with higher divergence which take more time to be aligned.

How did it end?

**Comment by AndreaGuarracino** [comment]
Hopefully, it ended well.
