### ISSUE TITLE
Cycles in graph

### ISSUE THREAD

**Issue by egoltsman** [pangenome/pggb#134]
Hello,
The first paragraph in the README mentions that the goal is a locally acyclic graph.  I recall seqwish not having this requirement, i.e. it used to happily built cyclic graphs.   Did the graph model change in seqwish or is it just being called with some constraints on cycles?   

This ticket suggests it might be the latter, but could you confirm?
https://github.com/ekg/seqwish/issues/19

Thank you for continuing your work in this direction!

**Comment by AndreaGuarracino** [comment]
Hi @egoltsman, you recall right that `seqwish` has no such requirement. The 'local acyclicity' is introduced during the smoothing phase with `smoothxg`, which locally applies Partial Order Alignments that result in acyclic graphs.
