### ISSUE TITLE
docker build error with MacBook Pro

### ISSUE THREAD

**Issue by zmz1988** [pangenome/pggb#137]
Hi! I trying to build an image following the instruction, with command line `docker build --target binary -t ${USER}/pggb:latest .` in pggb directory, but I get an error as following:

` ...
#8 40.71 [ 85%] Building CXX object CMakeFiles/seqwish.dir/src/main.cpp.o
#8 40.71 [ 85%] Building CXX object CMakeFiles/seqwish.dir/src/utils.cpp.o
#8 40.71 [ 86%] Building CXX object CMakeFiles/seqwish.dir/src/seqindex.cpp.o
#8 40.71 c++: error: unrecognized command-line option '-mcx16'
#8 40.71 c++: error: unrecognized command-line option '-mcx16'
#8 40.71 gmake[2]: *** [CMakeFiles/seqwish.dir/build.make:82: CMakeFiles/seqwish.dir/src/utils.cpp.o] Error 1
#8 40.71 gmake[2]: *** Waiting for unfinished jobs....
#8 40.71 gmake[2]: *** [CMakeFiles/seqwish.dir/build.make:95: CMakeFiles/seqwish.dir/src/main.cpp.o] Error 1
#8 40.71 c++: error: unrecognized command-line option '-mcx16'
#8 40.71 gmake[2]: *** [CMakeFiles/seqwish.dir/build.make:108: CMakeFiles/seqwish.dir/src/seqindex.cpp.o] Error 1
#8 40.71 [ 87%] Building CXX object CMakeFiles/seqwish.dir/src/paf.cpp.o
#8 40.72 c++: error: unrecognized command-line option '-mcx16'
#8 40.72 gmake[2]: *** [CMakeFiles/seqwish.dir/build.make:121: CMakeFiles/seqwish.dir/src/paf.cpp.o] Error 1
#8 40.72 gmake[1]: *** [CMakeFiles/Makefile2:454: CMakeFiles/seqwish.dir/all] Error 2
#8 40.72 gmake: *** [Makefile:149: all] Error 2
------
executor failed running [/bin/sh -c git clone --recursive https://github.com/ekg/seqwish     && cd seqwish     && git pull     && git checkout 6da2102     && git submodule update --init --recursive     && cmake -H. -Bbuild && cmake --build build -- -j $(nproc)     && cp bin/seqwish /usr/local/bin/seqwish     && cd ../]: exit code: 2
`

Could you please help me with this problem? Thanks a lot in advance!

**Comment by ekg** [comment]
It looks like your GCC (in docker?) Doesn't have the -mcx16 flag.

**Comment by subwaystation** [comment]
Hi @zmz1988,

for me `docker build --target binary -t ${USER}/pggb:latest .` works with the latest `pggb` commit. The `Dockerfile` itself is designed in a way to already have the GCC version incorporated that's required to compile `seqwish`.
So my impression is that you maybe changed the `Dockerfile`? 
Did you just go for
```
git clone --recursive https://github.com/pangenome/pggb
cd pggb
docker build --target binary -t ${USER}/pggb:latest .
```
?
Or it could be your hardware does not support `-mcx16`. But that seems very unlikely: https://superuser.com/questions/187254/how-prevalent-are-old-x64-processors-lacking-the-cmpxchg16b-instruction.

**Comment by ekg** [comment]
We should support arm64!

**Comment by zmz1988** [comment]
Oh I didn't take the warning message so seriously, when I tested the test file! Now I know the problem! I will change to a computer with Intel core and try! 

Thanks a lot! Also looking forward to the version that can support arm64!

**Comment by subwaystation** [comment]
@zmz1988 Please tell us, if switching the machine architecture worked for you :)

**Comment by zmz1988** [comment]
@subwaystation Works smoothly in MacBook with Intel core i7!

**Comment by subwaystation** [comment]
Thanks for letting us know! Have fun building graphs ;)

The support of arm64 is not on a very close horizon, so I am closing this issue.
