### ISSUE TITLE
Suggestion for 1D graph visualisation

### ISSUE THREAD

**Issue by brettChapman** [pangenome/pggb#146]
Hi

I've been using the 1D graph visualizations to identify regions of high variation across the pangenome graph, and also slicing the pangenome graph by different germ plasm (I'm working with Barley), to identify striking differences between groups of haplotypes (see attached 2 different haplotype groups for examples).

My question is, is there a way to add chromosome coordinates to the visualisation, so that I can then proceed to narrow in on specific regions of interest. I know a common coordinate across the entire pangenome can be based on a consensus graph coordinate, but perhaps there could be node ID on the x axis in major/minor ticks or some estimate of the number of Mbps from the start to end of the chromosome, just to give a ball-park idea of the region to zoom into.

Thanks.

![barley_pangenome_graph_7H og rowtype6 viz_inv](https://user-images.githubusercontent.com/8529807/144535714-ff81e871-8d94-48a7-90f0-9ce9cf03f725.png)

![barley_pangenome_graph_7H og rowtype2 viz_inv](https://user-images.githubusercontent.com/8529807/144535728-ca57a891-c38e-462b-a92e-c7d68dfc47b2.png)

**Comment by brettChapman** [comment]
Is there any way to add genomic coordinates to the 1D graph image, much like mashmap produces coordinates from a pairwise alignment? We could potentionally provide a chosen reference path to refer to the genomic coordinates for the visualization. At the moment this is a bottleneck for further analysis we're carrying out based on the 1D pangenome graphs, like the ones I provided earlier above. Alternatively, is there a tool I can use on the PAF files generated during the PGGB run which could help. Thanks.

![Morex_v2_chr1H_ZDM02064_v1_chr1H_pangenome_1H_pctid-95](https://user-images.githubusercontent.com/8529807/150301596-68b1d61f-efca-4f88-88fd-cef8ccc2c0c1.png)

**Comment by ekg** [comment]
Totally agree. We need to force a reference order and/or show the reference
order more clearly in the odgi viz view.

To not get blocked though, I'll suggest something already ready:

I usually use the 2D plots like this to understand pairwise relationships.

You can obtain them using odgi untangle, which optionally writes PAF
format. You'll need to choose the target and query paths.

**Comment by brettChapman** [comment]
Thanks @ekg, I look forward to seeing something implemented in PGGB.

For now I'm using ```odgi untangle``` to get the PAF files and then I'm visualising the chromosome coordinates of inversions and gaps in the reference using dot plot tools such as D-Genies, to come up with a scale to overlay on the 1D pangenome graph plots. We're currently writing up a paper, and having a scale to refer to in the figure is essential. Thanks.

**Comment by subwaystation** [comment]
@brettChapman there is now a method to sort a graph with `odgi` by a given reference path or by given reference paths. See https://odgi.readthedocs.io/en/latest/rst/tutorials/sort_layout.html#visualize-the-mhc-by-path-position.
