### ISSUE TITLE
Using pggb

### ISSUE THREAD

**Issue by champ1994** [pangenome/pggb#151]
How to use pggb ?

**Comment by ekg** [comment]
The best way to do this is to build the graph with pggb and then add variants in using vg add. Let us know if that works for you.

**Comment by champ1994** [comment]
Hi @ekg  , sorry for the late reply. 
Construction of the graph using pggb ran smoothly, but when trying to add the VCF to the graph, following error was raised:
  what():  No samples in variant at 21:5033870; can't make haplotypes
