### ISSUE TITLE
Core dump when using smoothxg from conda::pggb-0.2.0-hdfd78af_0

### ISSUE THREAD

**Issue by songtaogui** [pangenome/pggb#152]
Hi, Erik

Thank you for providing lots of wonderful pangenome related tools.

Recently, I was trying the pggb pipeline. However, the pipeline failed in the smoothxg step, with `Illegal instruction (core dumped)` error, after checking the generated `core.` file, I got the message below:

```
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `smoothxg -t 8 -T 8 -g pggb/all.fa.57209dc.2ff309f.seqwish.gfa -w 39351 -K -X 10'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x000055643e10c127 in std::__fill_bvector (__x=<optimized out>, __last=13, __first=0, __v=0x2b930e9cf788)
    at /opt/conda/conda-bld/smoothxg_1637224140228/_build_env/x86_64-conda-linux-gnu/include/c++/9.4.0/bits/stl_bvector.h:401
401     /opt/conda/conda-bld/smoothxg_1637224140228/_build_env/x86_64-conda-linux-gnu/include/c++/9.4.0/bits/stl_bvector.h: No such file or directory.
```

My conda environment was created with pggb-0.2.0-hdfd78af_0.

I have also ran the same pipeline using the docker image, and got the same core dump error.

So, what did I miss and how could I fix the error?

Please also find attached the log files for the pggb pipe if it would help.
[pggb.log](https://github.com/pangenome/pggb/files/7877620/pggb.log)

Thank you

Best wishes

Songtao Gui

**Comment by ekg** [comment]
This looks like a binary incompatibility with your processor.

Is there any chance you could run the docker build locally? That'd fix
this.

**Comment by songtaogui** [comment]
:Thank you for your kind help.

Unfortunately, I cannot run the docker build locally due to the root permissions on out cluster. Instead, I build a singularity local image from the pggb docker hub and ran it locally. However, I again encountered the same error:
![pggb-sglrty](https://user-images.githubusercontent.com/14274330/149699720-e644d5a0-11f1-4ab7-9a8b-99a13e06c386.png)

**Comment by ekg** [comment]
Can you build the individual tools on your system? Can your administrator
build them for you?

There is a processor level incompatibility. In general this is only
possible to resolve if you can build on the system itself.

**Comment by AndreaGuarracino** [comment]
@songtaogui, do you still have the same problems with the last `pggb 0.3.1` on Docker/bioconda?

**Comment by AndreaGuarracino** [comment]
Version 0.3.1 on bioconda fixed a number of compatibility issues.
