### ISSUE TITLE
Parameters selection suggestions for highly divergenet plant genome

### ISSUE THREAD

**Issue by baozg** [pangenome/pggb#153]
Hi, @ekg 

I try the different combinataion of parameters follow your suggestions and by this issue (#148) for chromosome 1 of a tetraploid genome (four haplotype). 
> Our major parameters are -s -p -n -l -k -G. We need to find a way to automatically adjust them. From @ekg:
> -p: We could use a crude estimate of divergence from the overall mash distances.
> -s: Could we look at autocorrelation in the sequences to find an -s bigger than repeats? Or can we increase -s as far as possible > without making the alignment problems too hard? Could wfmash find this threshold?
> G: TODO
> -l: TODO
> -k: TODO
> n: Usually this is the number of haplotypes. If the input are genome assemblies, this might be challenging to detect automatically.

Basically, I set the `-p 90 -n 3 -l 0` and try different length (-s 20k/50k/100k), it seems the 20k/50k are very fragment and make the graph very complicated in most region. I use the `pafplot` (https://github.com/ekg/pafplot) to plot with different wfmash paf. The paf show a good collinerirty bascially in every `segement` with a lot of INS/DEL region, but the gfa show very different. I look the distribution of annotated repeat from the EDTA pipeline (https://github.com/oushujun/EDTA,focus on the transopon element), it seems the longest repeat is just 87kb , mostly annotated repeat are less than 20kb. 

- `-s 20k`
![chr1 fa 8909426 wfmash paf](https://user-images.githubusercontent.com/20680150/149712195-4c1f1e55-d65f-41b9-addb-438d8cedf0e5.png)
![chr1 fa d2a6b54 2ff309f a9c39c9 smooth og viz_slide](https://user-images.githubusercontent.com/20680150/149712214-e8822159-a714-4bd4-a40d-272a8ff18397.png)
![chr1 fa d2a6b54 2ff309f a9c39c9 smooth og lay draw_mqc](https://user-images.githubusercontent.com/20680150/149712219-fa15be1c-f274-4099-9701-a7f0c91753f5.png)

- `-s 50k`
![chr1 fa d22559b wfmash paf](https://user-images.githubusercontent.com/20680150/149712240-2cc5860a-5130-4974-a126-ba81c1ef2471.png)
![chr1 fa d22559b 2ff309f a9c39c9 smooth og viz_slide](https://user-images.githubusercontent.com/20680150/149712253-0ec604bd-7b42-48b3-ab73-5c3dcad3e9e1.png)
![chr1 fa d22559b 2ff309f a9c39c9 smooth og lay draw_mqc](https://user-images.githubusercontent.com/20680150/149712265-d026b850-ab09-461c-95fd-2843866f68bc.png)

- `-s 100k`
![chr1 fa 8909426 wfmash paf](https://user-images.githubusercontent.com/20680150/149712317-39836ab9-db72-48d4-bd99-5fe2e35feab7.png)
![chr1 fa 8909426 2ff309f a9c39c9 smooth og viz_slide](https://user-images.githubusercontent.com/20680150/149712328-02d654b2-9e81-44e9-955a-cc80784af4bb.png)
![chr1 fa 8909426 2ff309f a9c39c9 smooth og lay draw_mqc](https://user-images.githubusercontent.com/20680150/149712347-b6935cb2-6fc6-4576-9957-0dfc951cfc54.png)

- Length distribution of annotated repeat from the EDTA pipeline 
![image](https://user-images.githubusercontent.com/20680150/149716851-01517f49-6688-4d3f-a1d4-f06ddd930857.png)

**Comment by ekg** [comment]
Could you share plots of the approximate mappings for the same PAFs? You
obtain them by adding -m to the wfmash run. Pafplot will work on that kind
of PAF as well.
