### ISSUE TITLE
How to keep the sequence order intact in the graph?

### ISSUE THREAD

**Issue by minalj365** [pangenome/pggb#160]
Hello!

I am building pangenome graphs for inversion regions in Atlantic herring. In the first case below (image 1a and 1b), I constructed 1b graph by reverse orienting all the sequences but keeping all parameters same. In 1b, the sequences that are near the breakpoint (green box in 1a) are placed at the end (green box in 1b). How can this be improved?

Image 1a:
![image](https://user-images.githubusercontent.com/57204282/155377358-4ff561a9-cfe8-488a-96da-88cf57073308.png)

Image 1b:
![image](https://user-images.githubusercontent.com/57204282/155377389-16af672a-2086-4b47-9100-086923e7ec8c.png)

I get similar issues in other graphs, which is leading to false interpretation of structural variations. Can you please suggest if there is a possible solution?

Thank you,
Minal

**Comment by baozg** [comment]
`odgi` can change order of sequence after graph building (https://github.com/pangenome/odgi/issues/354)

**Comment by subwaystation** [comment]
Did @baozg comment help you @code-acc?

**Comment by AndreaGuarracino** [comment]
@code-acc are these `odgi viz` visualization complete? I want to be sure to see also the graph topology (black lines on the bottom).

If I understand correctly, yours is a node sorting problem, which affects the 'horizontal order' of the nodes in the visualization. Probably, @baozg meant that you can change the 'vertical order' of the paths in the visualization.

**Comment by code-acc** [comment]
Thanks all, for your comments! As @AndreaGuarracino mentioned, it is a node sorting problem. I want to keep the horizontal order intact. Please let me know if there is any way to do so.

**Comment by AndreaGuarracino** [comment]
@code-acc, can you show us the images 1a and 1b by including also the graph topology (black lines on the bottom)?

This is an [odgi](https://github.com/pangenome/odgi) issue.  With the current `odgi sort` command you probably won't be able to do much to control the horizontal node order more for now. We have planned to resume working on the node sorting algorithms soon, so I expect (and hope) to be able to give you a better answer (and related command lines) in a few weeks/months.

**Comment by code-acc** [comment]
Hi @AndreaGuarracino! Looking forward to it. Here are the images with graph topology:
1a:
![image](https://user-images.githubusercontent.com/57204282/169738427-6d05a5ac-3701-4ed5-b690-9e79d029840e.png)

ab:
![image](https://user-images.githubusercontent.com/57204282/169738490-7232bda5-33c5-43cc-bb74-0a55f84863e6.png)

**Comment by AndreaGuarracino** [comment]
@code-acc, here is a partial answer: you may alleviate such a problem by sorting your graph with respect to a specific path (or set of paths). Take a look at the tutorial https://odgi.readthedocs.io/en/latest/rst/tutorials/sort_layout.html#d-reference-guided-grooming-and-reference-guided-sorting.
