### ISSUE TITLE
How to deal with dual assembly [question]

### ISSUE THREAD

**Issue by baozg** [pangenome/pggb#161]
Hi,

Chromosome-scale phasing need another data type.
The hifiasm HiC phasing paper introduce a new mode for assembly (http://lh3.github.io/2021/10/10/introducing-dual-assembly)?  
Can we use dual assembly with haplotype? Scaffold hap1 and hap2 with synteny and follow the [PanSN-spec](https://github.com/pangenome/PanSN-spec) to build pangenome graph. 
Did it vaild any assumption of pggb or vg ?

Thanks.

**Comment by subwaystation** [comment]
Hi @baozg,

I don't think there will be issues regarding the naming scheme. In principle, having a true phased assembly or a dual assembly, the naming scheme seems to be the same. So I would not expect any additional issues using dual assemblies.

Best,
Simon

**Comment by baozg** [comment]
Thanks for reply.
