### ISSUE TITLE
building a panviral genome

### ISSUE THREAD

**Issue by aliakeefe** [pangenome/pggb#163]
Hello, I downloaded the MERS genome from https://www.ncbi.nlm.nih.gov/datasets/coronavirus/genomes/. Given the fasta file, how do I build the panviral genome? Would my parameters be different? Ideally, I would like to obtain a vcf file from this as well, to build variation graphs on the vg tool kit. 
Thanks!

**Comment by AndreaGuarracino** [comment]
Just follow the introductory tutorial here https://pggb.readthedocs.io/en/latest/rst/quick_start.html to get pangenome graphs. The `-V` will allow you to emit VCF files as well.

**Comment by AndreaGuarracino** [comment]
As for the parameter values, it depends on the divergence in the data set. If it's not too high, the default values (10% divergence) may already be fine. Moreover, having non-large genomes, avoid using too large segment sizes (`-s`).
