### ISSUE TITLE
 linear visualization by reference

### ISSUE THREAD

**Issue by jia-wu-feng** [pangenome/pggb#171]
I would like to use a reference genome to rank the linear visualization in the pan-genome graph, is it possible?

Thanks.

**Comment by subwaystation** [comment]
Hi there @jia-wu-feng.

Unfortunately, at the moment the layout algorithm in ODGI https://odgi.readthedocs.io/en/latest/rst/tutorials/sort_layout.html does not have this feature implemented. However, we plan to add this in the future.

I added https://github.com/pangenome/odgi/issues/380 to keep track of this.

**Comment by ekg** [comment]
To be clear, it would be relatively easy to make this modification. We would want an input of paths and weights, to define how important each is. It will take a little work, but it's a frequently-requested feature.

Usually, features in the pipeline will tend to make the ordering match the first genome(s) that are put in, in the order that they appear in the FASTA file.

Also, note that there is `odgi untangle`, which can project the graph into pairwise alignments against chosen references. That will help to precisely evaluate a much simpler model than the full graph.
