### ISSUE TITLE
Is a way to use minimap2 for pggb

### ISSUE THREAD

**Issue by XuewenWangUGA** [pangenome/pggb#18]
Is a way to use minimap2 seqeuence aligner for pggb pipeline?
Detailed steps will be very helpful.
Thanks.

**Comment by ekg** [comment]
You'd want to replace the mapping step with it. The first iterations of
this pipeline used it.

The only thing that you might want to do is filter the alignments it makes
by block length, selecting a length longer than the length of common
repeats in the genomes you are working with.

**Comment by subwaystation** [comment]
@XuewenWangUGA Is this resolved?

**Comment by ekg** [comment]
We can support this by taking a PAF in input. I will add this.
