### ISSUE TITLE
gsl dependencies issue in conda package

### ISSUE THREAD

**Issue by soungalo** [pangenome/pggb#196]
Hello,  
I installed pggb (v. 0.3.1) using conda. Installation completed successfully, however when I try running pggb I get the following error:
```
wfmash: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Command exited with non-zero status 127
wfmash -X -s 100k -p 97 -n 1 -t 60 chr1H.fa chr1H.fa
0.00s user 0.00s system 0% cpu 0.48s total 208Kb max memory
```
Looking at the files in the lib/ of my conda env, I see libgsl.so.27 is there. I tried downgrading to gsl v2.5, but looks like there is a dependency issue:
```
Encountered problems while solving:
  - package wfmash-0.8.2-h144baf3_0 requires gsl >=2.7,<2.8.0a0, but none of the providers can be installed
```

Any idea how to get out of this loop? I could just build from source, but would prefer to use conda.  
Thanks!

**Comment by AndreaGuarracino** [comment]
As in #200, it is not always clear (to me) how to fix conda's dependencies. @piosierra (I am tagging you also here in case you know how to fix the problem) had dependency problems, and he solved them by using:

`conda install -c bioconda -c conda-forge pggb`

Could you please try this way?

**Comment by soungalo** [comment]
Unfortunately, this does not solve the problem.
I've also tried specifying previous versions (0.3.0 and 0.2), but keep getting the same error.
Any other suggestions?

**Comment by subwaystation** [comment]
Which conda version are you running? Maybe it is too old?

**Comment by soungalo** [comment]
Just updated to newest version (4.12.0) and retried, but got the same error.
If you have a working conda env of PGGB, could you maybe upload its yaml file? You can get it by activating the env and then running `conda env export > environment_droplet.yml`.

**Comment by subwaystation** [comment]
```
pggb) [heumos@savasana ~]$ conda install -c bioconda -c conda-forge pggb=0.3.1
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0

Your installed version is: 2.35
```

I don't feel lucky today. My initial environment was created via `conda create -n pggb python=3.10`. I am also confused, because my installed version should match the requirements.

**Comment by subwaystation** [comment]
Alright, I got it running with 

```
conda create -n pggb python=3.9
conda activate pggb
conda install -c bioconda pggb=0.3.1
pggb -i data/HLA/DRB1-3123.fa.gz -p 70 -s 3000 -G 2000 -n 10 -t 16 -v -V 'gi|568815561:#' -o out -M
```
Below the environment file.
[environment_droplet.yml.txt](https://github.com/pangenome/pggb/files/8716262/environment_droplet.yml.txt)

I suspect `python=3.9` is required. See https://stackoverflow.com/questions/63734508/stuck-at-solving-environment-on-anaconda or https://github.com/conda/conda/issues/9367.

Could you please try @soungalo? Thanks!

**Comment by subwaystation** [comment]
One last option: Remove all `gsl` packages you have installed or cached already via `conda clean`. Then try my suggestion above again. Or try `mamba`.

Else I am happy that my yaml file worked! :)

**Comment by huahua20** [comment]
a

**Comment by Shixuan-SU** [comment]
try conda install -c conda-forge gsl==2.7
