### ISSUE TITLE
PGGB discarding SNPs and Small InDels

### ISSUE THREAD

**Issue by VLoegler** [pangenome/pggb#215]
Is there a way to not take SNPs and small INDELs into account in the final graph ?
I am looking for a way to have a Pangenome graph with only structural variants and translocations. 
Thanks!

**Comment by ekg** [comment]
There is a currently hidden option to make a consensus graph. It's enabled with -C.

It's hidden because it seems that it sometimes breaks and we haven't had time to debug it

You can use this by following the hidden help text in the pggb script.

Something ilke `pggb -C cons,100` should give you what you're interested in. This will be an additional graph written to the output directory.

```
    #echo "    -C, --consensus-spec SPEC   consensus graph specification: write consensus graphs to"                         
    #echo "                                BASENAME.cons_[spec].gfa; where each spec contains at least a min_len parameter"  
    #echo "                                (which defines the length of divergences from consensus paths to preserve in the" 
    #echo "                                output), optionally a file containing reference paths to preserve in the output," 
    #echo "                                a flag (y/n) indicating whether we should also use the POA consensus paths, a"    
    #echo "                                minimum coverage of consensus paths to retain (min_cov), and a maximum allele"    
    #echo "                                length (max_len, defaults to 1e6); implies -a; example:"                          
    #echo "                                cons,100,1000:refs1.txt:n,1000:refs2.txt:y:2.3:1000000,10000"                     
    #echo "                                [default: off]"                                                                   
```

**Comment by ekg** [comment]
I caution that this will still leave nodes that are as long as the POA target length, and there can be SNPs between them. A method that works directly on the PGGB graph output (generic GFA) would seem to be better. It would be amazing if someone developed a generic method to do this.

**Comment by VLoegler** [comment]
Thanks for the answer!
