### ISSUE TITLE
DRB1-3123 example not producing a nice graph anymore after `biwflambda` update.

### ISSUE THREAD

**Issue by subwaystation** [pangenome/pggb#232]
Using the Dockerfile from https://github.com/pangenome/pggb/pull/231 I get quite an ugly DRB1-3123 graph:

![DRB1-3123 fa gz b1e1a2d 417fcdf a8de103 smooth final og lay draw_multiqc](https://user-images.githubusercontent.com/10184961/191264955-d0a80eec-ccca-4130-bf79-28722c940dd8.png)

```
docker pull ghcr.io/pangenome/pggb:latest
docker run -it -v ${PWD}/data/:/data ghcr.io/pangenome/pggb:latest "pggb -i /data/HLA/DRB1-3123.fa.gz -p 70 -s 3000 -G 2000 -n 12 -t 16 -o /data/bi_wfmash_test -M -m"
```

**Comment by ekg** [comment]
What happens with default parameters?

**Comment by subwaystation** [comment]
![image](https://user-images.githubusercontent.com/10184961/191682496-53d9f907-bb09-4179-9220-1ba73c692b3c.png)

```
docker run -it -v ${PWD}/data/:/data ghcr.io/pangenome/pggb:latest "pggb -i /data/HLA/DRB1-3123.fa.gz -n 12 -t 16 -o /data/bi_wfmash_test_1 -M -m
```

Other fancy graphs.

**Comment by subwaystation** [comment]
Alright, I got a nice one with this:

```
docker run -it -v ${PWD}/data/:/data ghcr.io/pangenome/pggb:latest "pggb -i /data/HLA/DRB1-3123.fa.gz -p 70 -s 2000 -G 2000 -n 12 -t 16 -o /data/bi_wfmash_test_2 -M -m"
```
![DRB1-3123 fa gz c666522 417fcdf a8de103 smooth final og lay draw_multiqc](https://user-images.githubusercontent.com/10184961/191683136-868e0fa3-6584-4379-a0ca-aab192ad6ca6.png)


A shorter `segment length` was required. I am happy now.

**Comment by ekg** [comment]
I'd suggest removing `-G`... that part is very different now. We actually iterate with very short `-G` three times. So we're just doing very local smoorthing now.

**Comment by subwaystation** [comment]
![image](https://user-images.githubusercontent.com/10184961/191695475-18097211-6a5a-459a-8c47-82b5f49ee80c.png)

Not sure this helped. The tip of the cavallo seems worse.
