### ISSUE TITLE
About the result study

### ISSUE THREAD

**Issue by ld9866** [pangenome/pggb#255]
Hello developers! pgggb is a very good software. At present, we have completed the construction of the chromosomal pan-genome. Now we have a puzzle, how should we conduct the subsequent analysis?
pggb is not like minigraph which gives us a generic sequence and we can do regular follow-up annotations looking at genes that aren't on the reference genome, so how do we do that?
Thank you!
Yours
Best day!

**Comment by AndreaGuarracino** [comment]
Hi @ld9866,

to better understand your request, could you please report here your detailed workflow with `minigraph`?

**Comment by ld9866** [comment]
Thank you for your prompt reply!
We use the https://github.com/AnimalGenomicsETH/bovine-graphs process, he finally provides us with a none-reference sequence.
We want to do some analysis of these sequences and try to find some key SV.
I wish good

**Comment by AndreaGuarracino** [comment]
Linking a whole repository is a bit heavy!

Running `pggb` will give you a `VCF` file with all the captured variants ([here](https://github.com/pangenome/pggb#quick-start) you can see a quick start for `pggb`). For other types of analysis, you can follow the tutorials [here](https://odgi.readthedocs.io/en/latest/rst/tutorials.html) and [here](https://pggb.readthedocs.io/en/latest/rst/tutorials.html).

**Comment by ld9866** [comment]
Thank you for your reply!
We will study and interpret the results.
Best
