### ISSUE TITLE
Question about the example "scerevisiae7.fasta.gz "

### ISSUE THREAD

**Issue by ld9866** [pangenome/pggb#256]
When we tested the software, we found that the tutorial generated an empty file. We don't understand why. We hope you can help us to see why.
Thank you！

Code: “wfmash scerevisiae7.fasta.gz -p 90 -n 6 -t 4 -m > scerevisiae7.mapping.paf”
Result: 
[wfmash::map] Reference = [scerevisiae7.fasta.gz]
[wfmash::map] Query = []
[wfmash::map] Kmer size = 15
[wfmash::map] Window size = 13
[wfmash::map] Segment length = 5000 (read split allowed)
[wfmash::map] Block length min = 15000
[wfmash::map] Alphabet = DNA
[wfmash::map] Percentage identity threshold = 90%
[wfmash::map] Mapping output file = /dev/stdout
[wfmash::map] Filter mode = 1 (1 = map, 2 = one-to-one, 3 = none)
[wfmash::map] Execution threads  = 4
[wfmash::skch::Sketch::build] minimizers picked from reference = 12004928
[wfmash::skch::Sketch::index] unique minimizers = 2043248
[wfmash::skch::Sketch::computeFreqHist] Frequency histogram of minimizers = (1, 258463) ... (1207, 1)
[wfmash::skch::Sketch::computeFreqHist] With threshold 0.001%, ignore minimizers occurring >= 563 times during lookup.
[wfmash::map] time spent computing the reference index: 2.96898 sec
[wfmash::skch::Map::mapQuery] mapped  -nan% @ 0.00e+00 bp/s elapsed: 00:00:00:00 remain: -2147483648:-3:-14:-8
[wfmash::skch::Map::mapQuery] count of mapped reads = 0, reads qualified for mapping = 0, total input reads = 0, total input bp = 0
[wfmash::map] time spent mapping the query: 5.98e-04 sec
[wfmash::map] mapping results saved in: /dev/stdout

**Comment by AndreaGuarracino** [comment]
@ld9866, you have an old version of `wfmash` installed. You can solve that by changing a bit the command line

`wfmash scerevisiae7.fasta.gz scerevisiae7.fasta.gz -p 90 -n 6 -t 4 -m > scerevisiae7.mapping.paf`

or by updating `wfmash` (recommended).
