### ISSUE TITLE
Annotating the 1D pangenome graph visualisation with centromere coordinates

### ISSUE THREAD

**Issue by brettChapman** [pangenome/pggb#258]
Hi

I was wondering if it would be possible to identify particular regions in the 1D pangenome graph visualisation to act as landmarks in the visualisation, such as identify the likely centromere, peri-centromeric regions etc?

Thanks

**Comment by AndreaGuarracino** [comment]
@brettChapman (I think you know by now that) you can use `odgi inject` to inject annotations as paths into the graph and they will become your landmarks in the visualization! A little example in the ODGI documentation: https://odgi.readthedocs.io/en/latest/rst/tutorials/injecting_gene_arrows.html#visualize-the-c4-graph-with-injected-gene-annotations
