### ISSUE TITLE
Use pggb to get fasta alignment for 20 1Mb genomes

### ISSUE THREAD

**Issue by bredelings** [pangenome/pggb#26]
Hi,

I tried using pggb to align 20 1Mb genomes, and it seems much faster that FSA!  My goal is to produce FASTA alignments that are better than I can get with FSA.  If there was a way to clean up FSA alignments by running POA on 1kb windows, that would probably work fine.

1. How can I generate FASTA files from the graphs?  It looks like the FASTA file should have the a similar layout to the 1D visualization.  The MAF alignments are really the same kind of thing.  I tried increasing the block size with `-s`, but this just seemed to generate weird alignments.

2. Preliminary inspection of the MAF alignments (using `less` :grimacing:) suggests that there is some over-alignment, mostly in aligning sequences to themselves (i.e. loops).  Is there a recommendation to eliminate or minimize this?

-BenRI

**Comment by bredelings** [comment]
If this is pending the arrival of the `-N` option, I could look at another branch.

**Comment by jnvaughn** [comment]
I have align 5 5MB genomes and get 22 out of  224 blocks with loops.  (This occurs with or without -N flag.)  All paths contain many re-used segments in forward orientation and therefore form cycles (Interestingly, we never see a segment used more than twice).  I could see this cycle behavior being desired - sibeliaz does a good job absorbing tandem repeats in this way - but the pggb result are less obvious.  I have attached a few examples.  pggb seems to refuse to smooth short, local (but not tandem) repeats creating these odd structures that, by my eye, need to be flattened.  Thanks for any advice.
[testDuplicates.txt](https://github.com/pangenome/pggb/files/6192330/testDuplicates.txt)

**Comment by ekg** [comment]
I'll check this out. The block merging was causing some issues in looping
regions but these will be resolved with the merge of the hybrid-map branch.
We have been getting pretty nice results for VNTRs with these fixes.

To reduce looping, you'll need to increase -s, increase -p, and increase
-w, -e, and -j. The alignments may not be able to consistently linearize
highly-similar repeats in of a VNTR, because the direct relationships
between the various copies may be ambiguous.

**Comment by ekg** [comment]
I have also seen some looping in STRs, which could be creating the effect
you're describing. Setting a higher (seqwish) -k can help. But I'll be
looking at this.

**Comment by jnvaughn** [comment]
Thanks very much.  pggb seems be doing well on STRs and VNTRs as evidence here and on some other simulated datasets.  The issue above is related more to small local repeats triggering a loop.  I have looked at one of the examples above in detail using flanking sequence (text file attached).  The little bit of loop-triggering homology is shown in red square in attached dotplot.  (On side note, block 700 in maf appears to be a spurious indel related to divergence.)  All gfas and raw sequences available at https://github.com/USDA-ARS-GBRU/PanPipes/tree/main/testSets/pggb_5_salmonella.    
[dotplot.pdf](https://github.com/pangenome/pggb/files/6198485/dotplot.pdf)
[blockContext.txt](https://github.com/pangenome/pggb/files/6198503/blockContext.txt)
