### ISSUE TITLE
Skip sequence partitioning?

### ISSUE THREAD

**Issue by fangbohao** [pangenome/pggb#278]
Hi, I was wondering if I could just skip the sequence partitioning because there is a chromosome-level genome provided by the VGP project. Could I just subset chromosomes based on the VGP reference genome for my HiFi haplotype contigs? Is there any hidden issue if I skip this step?

Thanks!
Bohao

**Comment by AndreaGuarracino** [comment]
Hi @fangbohao, you can skip the partitioning, it is not a mandatory step. We recommend creating subsets of contigs, when possible and if it makes sense for the specific analysis, to reduce the computational work for PGGB.

**Comment by fangbohao** [comment]
Thanks for your comments, Andrea!
