### ISSUE TITLE
Add/remove one assembly (or more) from a pangenome graph

### ISSUE THREAD

**Issue by LiaOb21** [pangenome/pggb#279]
Dear developers,

I was wondering if there is a way to add or remove assemblies to an already built pangenome graph using pggb.
I had a look to the documentation but I couldn't find anything. 
Sorry if I missed something and thank you in advance!

Lia

**Comment by subwaystation** [comment]
Dear @LiaOb21,

if you want to remove paths from the graph, please take a look at https://odgi.readthedocs.io/en/latest/rst/commands/odgi_extract.html. `-p, --paths-to-extract=FILE` should be your friend.

If you want to add assemblies you could theoretically map against the graph using https://github.com/maickrau/GraphAligner. I think with `vg augment` or `vg inject` you can embed the mappings in the graph. However, we do not recommend this. If you want to add assemblies, please build the graph again from scratch. This is the most precise way to do it.

**Comment by LiaOb21** [comment]
Hi @subwaystation,

Thank you so much for your suggestions.
Best regards,

Lia
