### ISSUE TITLE
Current versions of smoothxg and pggb on bioconda incompatible

### ISSUE THREAD

**Issue by lrvdijk** [pangenome/pggb#294]
Hi,

I was trying to run pggb on a data set, and installed it using bioconda.

However, when I tried to run it, I got the following error:

```
Flag could not be matched: 'S'
  smoothxg {OPTIONS}

    smoothxg: collinear block finder and graph consensus generator
    v0.7.0-0-g66d3044

...

Command exited with non-zero status 1
smoothxg -t 16 -T 16 -g output/parents_plus_HapV.fasta.gz.e792ba7.417fcdf.seqwish.gfa -r 51 --base output --chop-to 100 -I .9000 -R 0 -j 0 -e 0 -l 700,900,1100 -P 1,19,39,3,81,1 -O 0.001 -Y 5100 -d 0 -D 0 -S -Q Consensus_ -V -o output/parents_plus_HapV.fasta.gz.e792ba7.417fcdf.d64f4c6.smooth.gfa
0.00s user 0.00s system 85% cpu 0.00s total 6460Kb max memory
```

When browsing through the commit history of `pggb`, I saw this commit, which implemented the fix for the new version of smoothxg:
https://github.com/pangenome/pggb/commit/8ed02da94b9703b40b29d8562ffd9ed6dd65e6d8

However, that commit is not included in a released version of pggb yet, so current available versions on bioconda are incompatible. Would it be possible to create a new (patch) release of PGGB to fix this incompatibility?

Thanks in advance!

**Comment by peterdfields** [comment]
Not sure about the long-term but in the mean time you can downgrade your version of smoothxg by doing `conda install smoothxg=0.6.8` to get past this error.

**Comment by AndreaGuarracino** [comment]
Sorry for that! Unfortunately, updating `pggb` on bioconda is slower and harder. I am working on that (struggling with the errors that bioconda returns).

**Comment by DininduSenanayake** [comment]
@AndreaGuarracino  Any chance you can a add a note to main READEME.md file with a referral to this under install with **Bioconda** section ?  ☺️

**Comment by AndreaGuarracino** [comment]
I wanted to fix it as soon as possible, but bioconda has become particularly evil, so I have to bow to your request. I've highlighted the problem in the `README` (see https://github.com/pangenome/pggb/pull/305).

**Comment by AndreaGuarracino** [comment]
Fixed with https://github.com/bioconda/bioconda-recipes/pull/41671.
