### ISSUE TITLE
can't run your example

### ISSUE THREAD

**Issue by samlipworth** [pangenome/pggb#3]
I followed the instructions to pull your docker file but get the following error when trying to run..

docker run -it -v /home/heumos/git/pggb/data/:/data ghcr.io/pangenome/pggb:latest "pggb -i data/HLA/A-3105.fa.gz -s 3000 -K 11 -p 70 -a 70 -n 10 -t 2 -v -l"

/usr/local/bin/pggb: line 99: /data/HLA/A-3105.fa.gz.pggb-s3000-p70-n10-a70-K11-k8-w10000-j5000-W0-e100.paf: No such file or directory

Any idea what's wrong?

**Comment by subwaystation** [comment]
Hi @samlipworth 

I just realized I hardcoded some of my personal paths into this example.... So docker expects a full path as an argument to `-v`: `If you intended to pass a host directory, use absolute path.`

Assuming you are in the `pggb` folder, please try the following:
Type `pwd` which gives you the path in the current directory, in my case: `/home/heumos/git/pggb`. Then you append `/data:/data` resulting in `/home/heumos/git/pggb/data/:/data`. What we do here is take our `data` folder in the `pggb` repository and mount it in the docker container under `/data`.

Please tell me if that helped you.

**Comment by samlipworth** [comment]
Oops yes sorry should have spotted that, yes working now thanks!

**Comment by subwaystation** [comment]
Thank you for pointing out that the documentation is not 100% helpful! I Will update it.

One more tip I just got from @Zethson:
https://github.com/mlf-core/mlf-core/blob/master/mlf_core/create/templates/mlflow/mlflow_pytorch/%7B%7B%20cookiecutter.project_slug%20%7D%7D/MLproject#L12
Use `${PWD}/data:/data` for a shortcut ;)
