### ISSUE TITLE
smoothxg Flag could not be matched: 'o'

### ISSUE THREAD

**Issue by heuermh** [pangenome/pggb#30]
Running from a Docker container built on `ghcr.io/pangenome/pggb:latest` as of today (22 Nov 2020)
```bash
$ smoothxg \
  -t 1 \
  -g DRB1-3123.pggb-s1000-p90-n10-a90-K16-k8-w10000-j5000-W0-e5000.seqwish.gfa \
  -w 10000 \
  -j 5000 \
  -e 5000 \
  -l 10000 \
  -o DRB1-3123.pggb-s1000-p90-n10-a90-K16-k8-w10000-j5000-W0-e5000.smooth.gfa \
  -m DRB1-3123.pggb-s1000-p90-n10-a90-K16-k8-w10000-j5000-W0-e5000.smooth.maf \
  -s DRB1-3123.pggb-s1000-p90-n10-a90-K16-k8-w10000-j5000-W0-e5000.consensus \
  -a \
  -C 5000
...
Flag could not be matched: 'o'
  smoothxg {OPTIONS}
```

Did this `-o` option go away recently?  If so, I assume the script should be updated to `> out.smooth.gfa`?

**Comment by heuermh** [comment]
Not the only problem
```bash
...
Argument 'N' received invalid value type
  'DRB1-3123.pggb-s1000-p90-n10-a90-K16-k8-w10000-j5000-W0-e5000.smooth.maf'

  smoothxg {OPTIONS}
```

**Comment by ekg** [comment]
I think the option may not be synced in to the docker image yet. Hold on.
Will be syncing everything in the coming days.

**Comment by subwaystation** [comment]
I just ran your example @heuermh including `-N -M` and it ran through successfully. 
I suspect you still have an old version of the docker image. Please try `docker pull ghcr.io/pangenome/pggb:latest` and then run your commands again.

We are already planning to release docker images with the current `pggb` GitHub hash to make debugging more efficient. This will also help us to build a better Dockerfile for the nf-core/pangenome pipeline.

**Comment by subwaystation** [comment]
We now have snapshots of our docker images :)
https://github.com/orgs/pangenome/packages/container/pggb/

**Comment by heuermh** [comment]
Works for me with a new pull of the `:latest` tag, thanks!
