### ISSUE TITLE
The graph does not look quite the same as the collinear results

### ISSUE THREAD

**Issue by Wwwwwwwyc** [pangenome/pggb#302]
One sequence does not appear to be aligned with the others. However, this sequence has good collinearity results with the reference.

ODGI 1D visualization
![image](https://github.com/pangenome/pggb/assets/129487030/00b014d8-f1d2-49ac-b032-ebaed2d44836)

collinearity results
![image](https://github.com/pangenome/pggb/assets/129487030/321ce23f-2c6b-4410-8bd6-13ab670ea524)

I used the following command, maybe I should lower the -s and -l parameters of the wfmash step?
`pggb -i chr${i}_pan.fa -o chr${i}.pan -n 9 -t 128 -p 90 -s 5000 -S -m -V '$ref:#' ;done`

**Comment by subwaystation** [comment]
On second thoughts, if you have very small input sequences, lowering `-s` might be the better option here.

**Comment by Wwwwwwwyc** [comment]
> Hi there @Wwwwwwwyc,
> 
> what should help is lowering `-s` as you mentioned. What I would try first is to lower `-p`. Maybe set it to `-p 85`. I don't have any insights about your organism, but I suspect that for your reference and this specific `sample1` the actual distance could be larger than 90%.

Thanks for the help, I will try to lower the -s and -p parameters respectively! Another small question is, is the -n parameter useless now? I actually have 34 samples, however I set n=9 and it doesn't seem to make a difference

**Comment by Wwwwwwwyc** [comment]
> On second thoughts, if you have very small input sequences, lowering `-s` might be the better option here.

The samples I used were all assembled to the chromosomal level, probably because the genome is too small (12M), I will try to lower the parameters, thank you again for your help

**Comment by subwaystation** [comment]
Assuming you have 34 haplotypes please set `n=34`. Because 34-1 is the maximum number of secondary alignments we expect. From our experience this works well.

**Comment by Wwwwwwwyc** [comment]
Thanks for your help. I think that the -N setting error caused the graph to be inconsistent with collinearity, and when I set N=34, the results were more consistent. For my species (similar to yeast), -p does not differ much from 80-90 and -s from 4000-5000

**Comment by Wwwwwwwyc** [comment]
Thanks for your help. I think that the -n setting error caused the graph to be inconsistent with collinearity, and when I set `n=34`, the results were more consistent. For my species (similar to yeast), -p does not differ much from 80-90 and -s from 4000-5000

**Comment by subwaystation** [comment]
Happy to hear :)
