### ISSUE TITLE
vcfwave not found

### ISSUE THREAD

**Issue by aijigekoukou-shen** [pangenome/pggb#312]
Hi
I downloaded pggb from Conda. I run pggb with the following command: "pggb -i in.fa -o output -n 2 -t 16 -p 90 -s 5000 -V 'PLAS:#:1000'". And I got an error like this: "/home/sparks-fly/biosoft/conda/envs/pggb/bin/time: cannot run vcfwave: No such file or directory
Command exited with non-zero status 127". What should I do? Thanks

**Comment by AndreaGuarracino** [comment]
Currently, pggb on conda is broken, see #294 and https://github.com/bioconda/bioconda-recipes/pull/40520.

About vcfwace, yes, it is still not available on bioconda. We are still not able to build it there, see https://github.com/bioconda/bioconda-recipes/pull/38860, https://github.com/bioconda/bioconda-recipes/pull/40759, https://github.com/bioconda/bioconda-recipes/pull/41003. @pjotrp will help in fixing this. Meanwhile, you could use the docker/singularity flavoir of pggb, which is complete and fully updated from yesterday.

**Comment by aijigekoukou-shen** [comment]
Thanks for your reply. I'll try docker/singularity.

**Comment by AndreaGuarracino** [comment]
@aijigekoukou-shen, I've fixed the issue. Now `vcflib`, and then also `vcfwave`, are on `bioconda`. I've updated `pggb` there: the version 0.7.0 has a working way to decompose VCF files now!
