### ISSUE TITLE
Visualizing  pangenome graphs

### ISSUE THREAD

**Issue by ssk2020311** [pangenome/pggb#33]
Hi,

I was wondering if it is possible to use your tool to visualize pangenome graphs generated via Pandora https://github.com/rmcolq/pandora

Thank you

**Comment by subwaystation** [comment]
If I understood `Pandora` correctly, it can break down the resulting pangenome into a VCF.
If so, I would suggest creating a variation graph using `vg construct` https://github.com/vgteam/vg with the FASTA reference and the VCF from `Pandora`. Translate it into GFA using `vg view`.
Then use `odgi build` and subsequently `odgi viz` to create a 1D visualization of your pangenome. `odgi layout` and `odgi draw` can render a 2D visualization of the pangenome. However, it might help to normalize your pangenome first using `smoothxg`.

If you are looking for interactive visualization methods of pangenomes in the GFA format, you can also take a look at
https://github.com/MoMI-G/MoMI-G/ which is great for the interactive visualization of reference centered pangenomes. Or https://github.com/vgteam/sequenceTubeMap. There is also https://rrwick.github.io/Bandage/ or https://github.com/ggonnella/gfaviz for interactive 2D visualizations. Pantograph https://graph-genome.github.io/ tries to be an interactive version of the `odgi viz` 1D visualization, but might not scale well enough. Depends on the pangenome size.
You can find a summary of visualization tools for pangenome graphs in section 6.1 of https://www.annualreviews.org/doi/abs/10.1146/annurev-genom-120219-080406.

I hope this helps!

**Comment by ssk2020311** [comment]
Thank you so much for your detailed guidance! I will take a look at all of those!
