### ISSUE TITLE
How to understand the vcf file output by PGGB？

### ISSUE THREAD

**Issue by Lucio-Yang** [pangenome/pggb#334]
Hi,
I ran PGGB to build a pan-genome map of wheat and got a VCF file. I want to know what “.” in the VCF represent.  If “0” represents consistency with the reference, then what does “.”  represent?  Is this site not aligned after multiple sequence alignment?

Thanks ！
![image](https://github.com/pangenome/pggb/assets/42206757/0f18cde3-8f7b-4f1b-b5b3-e5b85a8fa5e0)

**Comment by AndreaGuarracino** [comment]
The "." means "missing genotype". For some reason, `vg` was not able to genotype the site. Usually, it is due to a missing alignment, but I suppose complex graph structures could put `vg` in difficulty as well.

**Comment by Drbiology** [comment]
> The "." means "missing genotype". For some reason, `vg` was not able to genotype the site. Usually, it is due to a missing alignment, but I suppose complex graph structures could put `vg` in difficulty as well.

Thank you for your quick reply ！
I still have a question: can the tanslocation or inversion be reflected in the graph or VCF obtained by PGGB, and how to count it?

**Comment by AndreaGuarracino** [comment]
You will see both of them in the graph. In the VCF, you can see the inversions after VCF decomposition with `vcfwave`. You can trigger the decomposition specifying the max allele length with the `-V` option (something like `-V reference:10000)`.
