### ISSUE TITLE
Edyeet -N no split and resolved memory issue with abPOA

### ISSUE THREAD

**Issue by brettChapman** [pangenome/pggb#37]
Hi Erik

I see you've added new options to edyeet and smoothxg.

Would using -N for no split with Edyeet be the same as setting the segment length to the length of the chromosome/genome? Would using -N reduce memory requirements and would there be an advantage to using -N over the default splitting the sequences by segment lengths? If so, why not set -N by default? I also see you've added an update to using abPOA. Has the memory issue with using abPOA been resolved now? Being able to use abPOA again would greatly reduce the memory overhead.

I have also just gained access to compute nodes in my cluster with 128GB RAM. Smoothxg jobs which failed before are now completing. I'm now testing with different Edyeet segment lengths and -a/-p parameters to see where the new memory limits are.

**Comment by ekg** [comment]
Hi Brett,

I was considering setting -N by default, but it seems that we can still run
into problems when aligning sequences with high divergence. More testing is
needed. It might be necessary to set a kind of bound on the difficulty of
the WFlign alignment problem to make sure it doesn't get stuck aligning
parts of sequences that are highly diverged.

If you have high identity, so -p is high, then it is easier to align long
sequences.

I have been testing -s 1000000 and see that this is slightly faster than -s
50000 before. So this update will allow you to set your segment length much
longer. But setting -N by default isn't yet possible (I think it's the way
pggb should work though).

As for abPOA, there were a bunch of updates in smoothxg that should make
that step easier. The current docker image for pggb isn't updated yet.
There are still some time (odgi graph ordering and rebuilding happens in
serial but should be in parallel) and memory issues in smoothxg that look
to be the last set of issues inhibiting scaling. For low coverage graphs
these might be less of an issue.

**Comment by brettChapman** [comment]
Hi Erik

Yeah, I've found a few gene regions in Barley to be highly divergent with large indels spanning several hundred bp. Trying to align such regions, even after adding 50Kbp/100Kbp either side of the gene, and then calling variants through VG deconstruct just doesn't work. I don't see the large indels in the variant calls.

Perhaps -N could be used after a first pass with an approximate mapping with -m. If large stretches of sequences are found to be highly divergent, then the -N parameter could be dropped?

I've started using your Docker image through Singularity. It's just easier to keep track and keep everything up to date.

**Comment by ekg** [comment]
Hi Brett,

That's basically how edyeet and wfmash work. First they run a step
equivalent to the -m flag, then those mappings are run with the alignment
algorithm. -m just sets the output file for mashmap to stdout and doesn't
run the second step.

I will add a field to the PAF with WFlign computation time so we can
investigate high-runtime alignments.

Maybe an intermediate filter like you're describing could be used to get a
better but slightly more expensive divergence estimate and filter on that
basis.

**Comment by brettChapman** [comment]
Hi Erik

That sounds like a good way to get around the problem of aligning highly divergent sequences.

I've found that while using -N my memory usage is like 10x higher.

I've been getting this error each time

```
757548.76s user 557.51s system 1593% cpu 47566.47s total 130187988Kb max memory
```

I'm going to try running -N with a very large segment length of 1,000,000 like you're currently testing with, and see how it performs. If edyeet still gets killed I'll have to drop -N on every run.

**Comment by ekg** [comment]
Keep in mind that -N will ignore -s. It will align the whole sequences. The
-s length will the only be a threshold at which we switch between a number
of secondary mappings defined for short sequences and that defined for long
ones (-n defines this).

Your memory usage experience looks correct.

**Comment by brettChapman** [comment]
Thanks for clearing that up. I'll avoid using -N. I'm now trying with a segment length of 1,000,000bp with no -N parameter. Could I feasibly go higher with the segment length to even a billion bp or more? I saw in another thread your discussion about removing false-positive links which is a direct result of short segment lengths. I have no doubt I would suffer from the same issues due to the high repetitive nature of the barley genome. However, you also highlight the problems with going higher than 100kbp due to slow alignments. Has this been addressed now with the updates to Edyeet, so I could go much higher with the segment length? Previously I found going higher with the segment length allows me to go lower with the alignment/mapping percent identity and keep within memory limits. I tried this before by using 150Kbp segment length and I could go down to 80% mapping/alignment percent identity. So it's a nice trade-off.

**Comment by ekg** [comment]
I actually think we will be able to set -N or arbitrary segment lengths for
the mashmap step. I found a bug that was generating low-identity mappings
in some cases where the target sequence is too short. This appears to be
the major remaining issue with scaling up the segment length or setting -N.

So yes, the goal is to allow end to end alignment if the contigs support
that. This may not always be the desired result, but it is important to be
able to set the segment length as needed.

**Comment by brettChapman** [comment]
Thanks. That sounds great! I'll keep an eye out on new edyeet updates. Does the PGGB docker image generally get updated soon after any updates to edyeet/smoothxg etc?

**Comment by subwaystation** [comment]
Edyeet is not part of PGGB anymore.

 @brettChapman We try to keep the docker image as cutting edge as possible.
