### ISSUE TITLE
Setting the poa-length-target(s)

### ISSUE THREAD

**Issue by jonahcullen** [pangenome/pggb#375]
Hello, thank you for providing and supporting this really excellent pangenome builder - the documentation is fantastic. I had one question regarding the ideal choice(s) for `poa-length-target`. I can see the default values are `700,900,1100` and was wondering from where those values came? For example, a [chicken pangenome](https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-023-01758-0) used `3079,3559` compared to a [human pangenome](https://www.nature.com/articles/s41586-023-05896-x) which used `13033,13177`.

Any advice or guidance for setting these value(s) would be greatly appreciated!

Thanks again,
Jonah.

**Comment by AndreaGuarracino** [comment]
@jonahcullen, they come from the consideration that a length of about 1 kbp is smaller than most nonlinear patterns of structural variation found in genomes, so we do not run the risk of excessively smoothing the graphs by default. There are no other general rules for the `poa-length-target` values. It also depends on the species, but humans are less likely to be overly smoothed than other species.
