### ISSUE TITLE
A null vcf file

### ISSUE THREAD

**Issue by dudududu12138** [pangenome/pggb#377]
Hello, 
I just test pggb on a simulated data. I simulated a reference file(.fasta), the length of this reference is 3941bp. Then I simulated a query file(.fasta),the length of this query is 600bp. This query sequence was taken from bases 1-300 and 800-1200 of the ref sequence. I use this 2 sequences to simulate deletion. But the final result report a null vcf file.
This is my code:
```
pggb -i tmp.fa -o output -n 2 -t 2  -p 50 -s 100  -V 'ref'
```
Below is the final vcf file:
![image](https://github.com/pangenome/pggb/assets/125525648/74e222e8-caf1-4c82-b4a7-ff2e3cc581c4)
And below is my simulated data which contains the reference and query sequences:
[tmp.txt](https://github.com/pangenome/pggb/files/14632579/tmp.txt)

**Comment by subwaystation** [comment]
@dudududu12138 I can reproduce. Your `*.seqwish.gfa` should contain still both your input sequences as paths. However, the `query` path is lost after the `smoothxg` step. @AndreaGuarracino you have any idea why?

**Comment by AndreaGuarracino** [comment]
Working on that! https://github.com/pangenome/smoothxg/pull/206
