### ISSUE TITLE
what dose "consensus path" generated with parameter -Q mean

### ISSUE THREAD

**Issue by yipukangda** [pangenome/pggb#378]
Hi,

pggb has a parameter *-Q* to give consensus path a prefix name in the `smoothxg` step, what dose "consensus path" mean and where could I find it(I searched in gfa file but get no results).

thanks

**Comment by AndreaGuarracino** [comment]
`smoothxg` can add (into the final graph) consensus sequences obtained by performing partial order alignment in each graph block during graph normalization. However, such a feature is currently disabled in `pggb`. I should probably hide the `-Q` parameter for a while!

**Comment by yipukangda** [comment]
Thanks, if I use `smoothxg` independently with this function, dose it mean this step could merge all similar sequence within a block into one?

**Comment by AndreaGuarracino** [comment]
@yipukangda, that was not a merge, but more than a consensus sequence that is representative of all sequences in that block.

Closing this, as such a feature is not supported anymore!
