### ISSUE TITLE
pggb: option requires an argument -- 'i'

### ISSUE THREAD

**Issue by RobStr12** [pangenome/pggb#379]
Hi,

I'm trying to build a pangenome using pggb version 0.5.2. For this I use following command line:

pggb -i ./Spider_mite/data/Spider_mite.fa -o ./Spider_mite/output/pggb/ -n 2

However, each time I get the same error:
pggb: option requires argument -- 'i'

But as you can see in the command, I've included the -i argument. Do you have an idea what could be the problem?

Extra info:
I'm running the commands in a Rocky Linux 9.3 (Blue Onyx) environment

**Comment by AndreaGuarracino** [comment]
That's strange! How did you install PGGB?
