### ISSUE TITLE
Issues with using PGGB output with VG or GraphAligner

### ISSUE THREAD

**Issue by briannadon** [pangenome/pggb#39]
I have a set of a few bacterial assemblies of a ~5mbp genome. My pggb run on the genome is quick and the results look good in the included visualizations. It's highly contiguous and the paths are reasonable.

However, I want to align short reads to the pangenome graph and call variants. When I use GraphAligner with the pggb graph and paired illumina short read data, I get reasonable read mapping (about 95% reads mapped), but the GAM output doesn't seem to work with `vg call`. I get completely blank or all "ref" or "0" calls in the resulting VCF. Is there a formatting issue when converting pggb's smoothxg output into .vg format I should be aware of? Seems like at some point the pggb graph isn't converting to vg correctly. 

An example of my piping is below, where `$gfa` is the smoothxg graph from pggb.

```
vg view -Fv $gfa > salm.vg
vg index -t 38 -x salm.xg salm.vg

GraphAligner --verbose -x vg -t 38 -g salm.vg -f $fq1 -f $fq2 -a salm.gam

vg pack -t 38 -x salm.xg -g salm.gam -Q 5 -o salm.gam.pack
vg call -d 1 -t 38 -m 1,2 -k salm.gam.pack -s SRR13061905 -a salm.xg > salm.xg.gam.vcf
```

**Comment by ekg** [comment]
Would you try using GAF output from GraphAligner? Can you manually check some alignments to verify they are correct?

Your conversion looks correct. You can also convert directly from GFA into XG. And, you can give the GFA from pggb to GraphAligner. This might simplify things. 

Maybe there is a problem with the filtering in pack? -Q 5 might remove everything if the qualities aren't as expected.

**Comment by briannadon** [comment]
I should update: either an update in PGGB or GraphAligner has allowed both to work nicely together now. I don't know what changed but I can confirm it works with all my test sets.
