### ISSUE TITLE
mismatched line lengths at line 3 within sequence 

### ISSUE THREAD

**Issue by Ahmad-40** [pangenome/pggb#398]
[vg autoindex] Executing command: vg autoindex --workflow giraffe -r /public/home/ahmad/outdir/in.fa.gz.bf3285f.11fba48.11fe66b.smooth.final.gfa -v /public/home/ahmad/outdir/in.fa.gz.bf3285f.11fba48.11fe66b.smooth.final.RAlphonso.vcf -p pangenome
[IndexRegistry]: Checking for phasing in VCF(s).
[IndexRegistry]: Chunking inputs for parallelism.
index file /public/home/ahmad//outdir/in.fa.gz.bf3285f.11fba48.11fe66b.smooth.final.gfa.fai not found, generating...
**ERROR: mismatched line lengths at line 3 within sequence** 
File not suitable for fasta index generation. Note the GFA file was obtained as a result of pggb run ( partition-before-pggb -i /public/home/ahmad/pangen/in.fa.gz \
    -o /public/home/ahmad/outdir \
    -n 5 \
    -t 15 \
    -p 90 \
    -s 5k \
    -V 'R:1000'). Here are more details of the file for consideration awk '{print length($0)}' /public/home/ahmad/outdir/in.fa.gz.bf3285f.11fba48.11fe66b.smooth.final.gfa
9
20
196
20
20
9
20
9
20
179
20
20
9
20
9
20
17
20
20
9
20
9
20
130
How to fix this issue?

**Comment by AndreaGuarracino** [comment]
@Ahmad-40, you are giving to `vg autoindex -r` a GFA file instead of a FASTA file!

```shell
vg autoindex
usage: vg autoindex [options]
options:
  output:
    -p, --prefix PREFIX    prefix to use for all output (default: index)
    -w, --workflow NAME    workflow to produce indexes for, can be provided multiple
                           times. options: map, mpmap, rpvg, giraffe (default: map)
  input data:
    -r, --ref-fasta FILE   FASTA file containing the reference sequence (may repeat)
...
