### ISSUE TITLE
Unable to generate giraffe indexes for PGGB graph

### ISSUE THREAD

**Issue by KopalliV** [pangenome/pggb#400]
I am trying to generate indexes for giraffe of a GFA file generated using PGGB but I am unable to do so. The process is getting killed before finishing.

Command for generating the graph:  pggb -i ./Chr1_combined.fasta.gz -n 7 -D temp/ -t 16 -o ./Chr1_pggb_default
Command used : vg autoindex -w giraffe --prefix pggb_real --gfa pggb.gfa -T ../../temp/

Error: 
vg autoindex -w giraffe --prefix pggb_real --gfa pggb.gfa -T ../../temp/
[IndexRegistry]: Checking for haplotype lines in GFA.
[IndexRegistry]: Constructing VG graph from GFA input.
[IndexRegistry]: Constructing XG graph from VG graph.
[IndexRegistry]: Constructing a greedy path cover GBWT
[IndexRegistry]: Constructing GBZ using NamedNodeBackTranslation.
[IndexRegistry]: Constructing distance index for Giraffe.
Killed

GBZ file is being generated but distance and minimizer indexes are not being generated.
Can somebody guide me if I am doing something wrong here.?

Vg version: v1.57.0-21-gdb574a520 "Franchini"

**Comment by AndreaGuarracino** [comment]
@KopalliV , `pggb`'s graphs are hard to digest for `vg giraffe`. I would suggest asking `vg`'s team for help about it!
