### ISSUE TITLE
The question about `vg` version of pggb

### ISSUE THREAD

**Issue by zwh82** [pangenome/pggb#415]
According to the `PGGB` Dockerfile, I believe `PGGB` should be compatible with the latest version of `vg`. However, `PGGB` on Bioconda still uses `vg` 1.40. I have a tool that needs to be uploaded to Bioconda, and it requires `PGGB` and `vg` version 1.52 or later. This creates a version conflict with `vg`. Is it possible to update the `vg` version of `PGGB` on Bioconda?
https://github.com/pangenome/pggb/blob/e8dd3fd3adffc3efcfc4f8ac0efc79cf0d54771b/Dockerfile#L103

https://github.com/bioconda/bioconda-recipes/blob/77e90150442fa23bfd227b88696ffc982be7abc0/recipes/pggb/meta.yaml#L31
```
requirements:
  run:
    - bc
    - tabix
    - gfaffix ==0.1.5b
    - gsl 2.7.0 
    - multiqc ==1.19
    - odgi ==0.8.6
    - pigz
    - bcftools
    - seqwish ==0.7.10
    - smoothxg ==0.7.4
    - time
    - vg 1.40.0
    - wfmash ==0.13.0
    - python-igraph ==0.10.4
```

**Comment by AndreaGuarracino** [comment]
That's right! Unfortunately, updating things on bioconda is often a pain, which is why we're slower there. I've just triggered the update of `vg` to v 1.59.0. After accepted and merged, it will take a bit before becoming available via bioconda.

**Comment by bgruening** [comment]
Why is updating Bioconda painful? :)

**Comment by AndreaGuarracino** [comment]
Every now and then, automatic updates (new GitHub releases that trigger Bioconda recipe updates) stop working, and it's not always easy to understand why. Then I start spying on other recipes to figure out what to fix. :/

**Comment by AndreaGuarracino** [comment]
@zwh82, pggb's recipe has vg 1.59.0, I hope everything will be fine now!

**Comment by zwh82** [comment]
Thanks. Everything is all right.
