### ISSUE TITLE
Question about pangenome building in species with high level of large translocations

### ISSUE THREAD

**Issue by GabrieleRigano99** [pangenome/pggb#421]
First of all, I'd like to thank you for the amazing work done!
Secondly, I'm working on a fungal species with very high levels of chromosomal polymorphism and large translocations (of Mbp), and I already built a pangenome using t2t gapless genome assemblies of 11 strains without dividing them by chromosome.
I was wondering if it would be possible (and correct) to build a new pangenome graph using also contig or scaffold-level assemblies.
If that's the case, should I only use assemblies without gaps or Ns to avoid introducing false haplotypes in the graph?
Thank you!

**Comment by AndreaGuarracino** [comment]
You can use both! We usually use contig-level assemblies, but some colleagues (I remember plant fans) use scaffold-level assemblies too. Ns will not introduce particular issues, just big bubbles with unaligned sequences.

**Comment by GabrieleRigano99** [comment]
Thank you so much for the fast response! This was a precious info.
