### ISSUE TITLE
Assertion `queryLen <= querySize' failed

### ISSUE THREAD

**Issue by ivaneskos** [pangenome/pggb#426]
Hi!
I have a strange error while running pggb for the dataset of 2142 short (43-61 kb) genomes. 
the error I have is in the alignment stage: 
```
[wfmash::align::computeAlignments] aligned 32.58% @ 1.59e+07 bp/s elapsed: 00:00:35:20 remain: 00:01:13:08wfmash: /opt/conda/conda-bld/wfmash_1711228780634/work/src/align/include/computeAlignments.hpp:510: void align::Aligner::doAlignment(std::stringstream&, align::MappingBoundaryRow&, const std::string&, const std::shared_ptr<std::__cxx11::basic_string<char> >&, uint64_t): Assertion `queryLen <= querySize' failed.
Command terminated by signal 6
```
I've checked the fasta sequences: ANI is high for all of them (above 95%). 

my command was:
pggb -i $all_genomes_dir/2119_plus_23_together_oneline.fasta -o $pggb_results_dir -n 2142 -p 95 -t 32
input fasta file + the log file are in https://drive.google.com/drive/folders/1d-otlKxHVP5jTml45Z-QO6d_n22NlhvP?usp=sharing 

Do you have any ideas about the origin of this error?
Thanks in advance for your help!

**Comment by ivaneskos** [comment]
Hi @AndreaGuarracino! Thanks for your help and check - it helped, I have my pangenome graph now! I had a report of duplicated IDs as a warning, not a critical error, and I haven't paid enough attention to it. Thanks a lot again!!

**Comment by AndreaGuarracino** [comment]
Enjoy pangenomics!
