### ISSUE TITLE
Reference sketch empty

### ISSUE THREAD

**Issue by danimelsz** [pangenome/pggb#427]
Hi

I am trying to use the following input data (test.fa):

> sp1
aatcg
> sp2
aattt
> sp3
aattg
>sp4
aatct

After indexing with samtools, I run "pggb -i test.fa -o . " but I always receive the following warning:

ERROR, reference sketch is empty. Reference sequences shorter than the segment length are not indexed
Command exited with non-zero status 1

What am I doing wrong?

**Comment by AndreaGuarracino** [comment]
@danimelsz, your sequences are tooooo short! `wfmash` is optimized to align contig-level sequences (hundreds/millions of base pairs). You can set `-s 100` in `pggb` and use sequences at least 100bp-long, or align your short sequences with another aligner and then use `pggb -i test.fa --input-paf alignment.paf -o .` to skip the alignment step.

**Comment by danimelsz** [comment]
Hello! Thank you for your response

How can I generate the alignment.paf? I only have the test.fa (aligned sequences in fasta format).

Thanks
