### ISSUE TITLE
Command terminated by signal 11

### ISSUE THREAD

**Issue by lt11** [pangenome/pggb#47]
Hi All,

I get an error while running pggb on 15 saccharomyces assemblies:

[smoothxg::create_consensus_graph] cleaning up redundant link paths
Command terminated by signal 11
smoothxg -t 132 -g /data/cp-full/multisaccha-prefix.fa.gz.pggb-s50000-p70-n10-a70-K16-k8-w10000-j5000-e5000-I0.seqwish.gfa -w 10000 -I 0 -j 5000 -e 5000 -l 10000 -m /data/cp-full/multisaccha-prefix.fa.gz.pggb-s50000-p70-n10-a70-K16-k8-w10000-j5000-e5000-I0.smooth.maf -s /data/cp-full/multisaccha-prefix.fa.gz.pggb-s50000-p70-n10-a70-K16-k8-w10000-j5000-e5000-I0.consensus -a -C 10,100,1000,10000 -o /data/cp-full/multisaccha-prefix.fa.gz.pggb-s50000-p70-n10-a70-K16-k8-w10000-j5000-e5000-I0.smooth.gfa
32771.07s user 727.37s system 2672% cpu 1253.48s total 20854404Kb max memory

Everything works fine if I reduce the number of assemblies (e.g. to 7).

I'm using a server with ~500 GB RAM, 176 cores, more than 10 TB of free temporary HDD storage.

Any suggestion?

Best,

Lorenzo

**Comment by ekg** [comment]
We are about to make a release. Would you mind trying again with the
updated version of the pipeline?

**Comment by lt11** [comment]
Hi All,

Any news about this thread?

Best,

Lorenzo

**Comment by AndreaGuarracino** [comment]
Hi Lorenzo, several fixes regarding time and memory usage have been fixed in the last few weeks. A little more patience, we will release a new version soon. Sorry for the delay.

**Comment by lt11** [comment]
Thanks guys! Looking forward for the new release!

**Comment by lt11** [comment]
Problem solved with the latest updates!

**Comment by ekg** [comment]
Nice!

**Comment by AndreaGuarracino** [comment]
@lt11, thank you for confirming it.
