### ISSUE TITLE
Issues in using pggb 

### ISSUE THREAD

**Issue by anna176577** [pangenome/pggb#48]
Hello,

I want to use `pggb` to make a graph pan genome by using 15 genomes. I tried to use `pggb `command line but not sure how to input multiple genomes. For example, in the following command line, how can I input all 15 genomes to create the output file. 

`pggb -i sample1.fa.gz -N -w 50000 -s 10000 -I 0 -p 70 -a 70 -n 5 -t 16 -v -l -o out`

I could not find a way to input multiple files in the document. 

Thank you for the help!

**Comment by subwaystation** [comment]
Hi @anna176577,
please put all your input genomes into one FASTA file. Then try:

```
pggb -i samples.fa.gz -N -w 50000 -s 10000 -I 0 -p 70 -a 70 -n 5 -t 16 -v -l -o out
```
Cheers!

**Comment by ekg** [comment]
Those settings for identity are very low. In practice this makes sense if
you have 10-20% divergence between your genomes.

If they are closer I suggest using a higher -p setting.

We will be making a release shortly. If you plan on further testing then I
would wait for that and use the recommended settings. (-a will go away and
so will the need to set -N).

**Comment by anna176577** [comment]
> Hi @anna176577,
> please put all your input genomes into one FASTA file. Then try:
> 
> ```
> pggb -i samples.fa.gz -N -w 50000 -s 10000 -I 0 -p 70 -a 70 -n 5 -t 16 -v -l -o out
> ```
> 
> Cheers!

Thank you @subwaystation! By putting all genomes together you mean merge or concatenate them? Thank you!

**Comment by anna176577** [comment]
> Those settings for identity are very low. In practice this makes sense if you have 10-20% divergence between your genomes. If they are closer I suggest using a higher -p setting. We will be making a release shortly. If you plan on further testing then I would wait for that and use the recommended settings. (-a will go away and so will the need to set -N).
> […](#)

Thank you for the suggestions @ekg! My samples are pretty diverse but I wanted to test the parameters first. I will keep following the updates.

**Comment by AndreaGuarracino** [comment]
I suppose this continues here #51.
