### ISSUE TITLE
seqwish issue in pggb command line

### ISSUE THREAD

**Issue by anna176577** [pangenome/pggb#51]
Hello All,

I am aligning multiple genomes to make a graph genome using:

`pggb -i in_file.fasta.gz -w 100000 -s 20000 -p 120 -a 70 -n 5 -t 16 -v -l out_file`

It runs the alignment step and generates corresponding `PAF` output file. However, for the `seqwish` step, it gives this error:

```
Passed in argument, but no positional arguments were ready to receive it: 8
  seqwish {OPTIONS}

    seqwish: a variation graph inducer

  OPTIONS:

      -h, --help                        display this help menu
      -a[FILE], --sxs-alns=[FILE]       induce the graph from these .sxs
                                        formatted alignments
      -p[FILE], --paf-alns=[FILE]       induce the graph from these PAF
                                        formatted alignments
      -s[FILE], --seqs=[FILE]           the sequences used to generate the
                                        alignments (FASTA, FASTQ, .seq)
      -b[BASE], --base=[BASE]           build graph using this basename
      -g[FILE], --gfa=[FILE]            write the graph in GFA to FILE
      -m[FILE], --match-list=[FILE]     use the sequence match list in FILE to
                                        subset the input alignments
      -o[BASE], --vgp-out=[BASE]        write the graph in VGP format with
                                        basename FILE
      -t[N], --threads=[N]              use this many threads during parallel
                                        steps
      -r[N], --repeat-max=[N]           limit transitive closure to include no
                                        more than N copies of a given input base
      -k, --keep-temp                   keep intermediate files generated during
                                        graph induction
      -d, --debug                       enable debugging

seqwish -t 16 -s in_file.fasta.gz -p in_file.paf -k 8 -g in_file.gfa -B 1000000 -P
```

From the above message, I understand, It is not recognizing options `-k -B -P` and I did not give these options in the `pggb` command line. I think it is automatically coming with some other parameter.  I am not sure how to avoid these parameters to make it run. Thank you for any help!

**Comment by AndreaGuarracino** [comment]
Hi @anna176577,
are you using the current master? In the last big update, the syntax is changed a bit. Now `-l number` is for specifying the minimum block length filter for mapping; to render a 2D layout of the graph, you have to specify `-L`. Moreover, `-p` has to be lower than or equal to 100: is `-p 120` on purpose? Try

```pggb -i in_file.fasta.gz -w 100000 -s 20000 -p 100 -a 70 -n 5 -t 16 -v -L -o out_file```

Note the `-o out_file` to specify the output folder too.

**Comment by anna176577** [comment]
> Hi @anna176577,
> are you using the current master? In the last big update, the syntax is changed a bit. Now `-l number` is for specifying the minimum block length filter for mapping; to render a 2D layout of the graph, you have to specify `-L`. Moreover, `-p` has to be lower than or equal to 100: is `-p 120` on purpose? Try
> 
> `pggb -i in_file.fasta.gz -w 100000 -s 20000 -p 100 -a 70 -n 5 -t 16 -v -L -o out_file`
> 
> Note the `-o out_file` to specify the output folder too.

Hi @AndreaGuarracino, I am using `pggb version 20201106`. I am not sure if that's the recent one. I think `-L `by default is `100`.   I have changed the value of `-p` as you suggested. I have added the `-o `option too. I will try it and see how it goes. Thank you!

**Comment by anna176577** [comment]
Hi @AndreaGuarracino,

I got the same error when I used the `pggb` command line that you suggested. Here is the `seqwish` command line that the error shows:

`seqwish -t 16 -s in_file.fasta.gz -p in_file.paf -k 8 -g in_file.gfa -B 1000000 -P`

**Comment by ekg** [comment]
Please make sure the git versions of the tools match those in the
Dockerfile. This looks like an old version of seqwish.

**Comment by anna176577** [comment]
I have tried using new version of `pggb `
`pggb -i in_file.fasta.gz -w 100000 -s 20000 -p 100 -a 70 -n 5 -t 16 -v -L -o out`

but now get the following error:
```Flag could not be matched: 'l'
  edyeet [target] [queries...] {OPTIONS}
```

**Comment by AndreaGuarracino** [comment]
@anna176577, the error indicates that you have a previous version of edyeet respect the version specified in the [Dockerfile](https://github.com/pangenome/pggb/blob/66ef0b1fe98700fdd17c46521e2a3a1b8964c717/Dockerfile#L30).

Coul you please update also your edyeet executable, and re-try? This is the commit in the Dockerfile specified for edyeet

[https://github.com/ekg/edyeet/commit/776a0c82e7ebf9ea7def055d12e19d6bb0aa5383](https://github.com/ekg/edyeet/commit/776a0c82e7ebf9ea7def055d12e19d6bb0aa5383)

**Comment by anna176577** [comment]
Hello,

I got the latest version of pggb and now I getting an out of memory error at the smoothxg step. I am already using 16 GB. Can you please suggest how to make it work? Thank you!

**Comment by AndreaGuarracino** [comment]
Wops! The latest updates have reduced the memory consumption, but 16GB may be too little depending on your dataset.  
Can you give us some more information? For example, how big is your input? Could you post the log too?

**Comment by anna176577** [comment]
So I am using one zipped `fasta` input file which is made by concatenating two individual `fasta` files. The zipped `fasta` file size is ~450 Mb. The parameters I am using are
`pggb -i input.fasta.gz -s 10000 -p 80 -a 70 -n 5 -t 16 -v -L -o out`

The log file is pretty big but I am putting last few lines here:
```
[seqwish::gfa] 3382.028 done
seqwish -t 16 -s input.fasta.gz -p out/output.paf -k 19 -g out/output.gfa -B 1000000 -P
[smoothxg::main] loading graph
[smoothxg::main] prepping graph for smoothing
[smoothxg::prep] building path index
[smoothxg::prep] sorting graph
[odgi::path_linear_sgd] calculating linear SGD schedule
[odgi::path_linear_sgd] calculating zetas for 10484 zipf distributions
[odgi::path_linear_sgd] 1D path-guided SGD: 100.00% @ 1.75e+06/s elapsed: 00:01:18:08 remain: 00:00:00:000
[odgi::groom] grooming: 100.00% @ 9.86e+05/s elapsed: 00:00:00:15 remain: 00:00:00:00
[odgi::groom] organizing handles: 100.00% @ 2.54e+07/s elapsed: 00:00:00:00 remain: 00:00:00:00
[odgi::topological_order] sorting nodes: 100.00% @ 1.13e+05/s elapsed: 00:00:02:16 remain: 00:00:00:00
[smoothxg::prep] chopping graph to 100
[odgi::chop] 1703932 node(s) to chop.
[smoothxg::prep] writing graph out/output.gfa
[smoothxg::main] building xg index
[smoothxg::smoothable_blocks] computing blocks
[smoothxg::smoothable_blocks] computing blocks for 20928423 handles: 100.00% @ 1.32e+05/s elapsed: 00:00:02:37 remain: 00:00:00:00
[smoothxg::break_and_split_blocks] cutting blocks that contain sequences longer than max-poa-length (10000)
[smoothxg::break_and_split_blocks] splitting 1499786 blocks at identity 0.000 (edlib-based clustering) and at estimated-identity 0.000 (mash-based clustering)
[smoothxg::break_and_split_blocks] cutting and splitting 1499786 blocks: 100.00% @ 7.06e+05/s elapsed: 00:00:00:02 remain: 00:00:00:00
[smoothxg::break_and_split_blocks] cut 12 blocks of which 0 had repeats
[smoothxg::break_and_split_blocks] split 0 blocks
[smoothxg::smooth_and_lace] applying global abPOA to 1499786 blocks: 12.71% @ 8.77e+01/s elapsed: 00:00:36:13 remain: 00:04:08:52smoothxg -t 16 -g out/output.gfa -w 10000 -M -J 0.7 -K -I 0 -R 0 -j 5000 -e 5000 -l 10000 -m out/output.maf -s out/output.consensus -a -C 10,100,1000,10000 -o out/output.gfa
7303.57s user 689.61s system 99% cpu 8016.92s total 16775904Kb max memory
```

**Comment by ekg** [comment]
It looks like you've hit 16GB and the process stopped.

Is there any way to break down the problem into smaller sub-problems? Do
you have a larger system available?

Barring those options, the first thing to try is to set up the block
splitting to prevent the collapse of divergent sequences into the same POA
problem. Try setting -I 0.6 -R 0.2. This will trigger a "split" of
sequences that, by edit distance, are >60% diverged over at least 20% of
the length of the shorter sequence in the pair. This re-clusters the
sequences going into POA so that each cluster is spanned by relationships
at least his good.

The result is that we get much lower memory usage during POA. Some
difficult blocks can grow to be very large graphs (for the direct
application of global POA). You can also try to increase these parameters.

**Comment by anna176577** [comment]
I tried your suggestion and now get an error for the same step but I think there is more job done now:
```
[smoothxg::smooth_and_lace] applying global abPOA to 1882444 blocks: 49.89% @ 1.19e+02/s elapsed: 00:02:11:31 remain: 00:02:12:08tee: standard output: Cannot allocate memory
tee: write error
```

Meanwhile, I am trying different combinations of these parameters to check if it runs through or not. Is it possible to run it in chunks of genome and combine later? For example, if I only use chromosome 1 for my input genome and run the script and repeat it for other chromosomes separately and combine the files later? Because ultimately, I will want to add more fasta files in my input file.

**Comment by AndreaGuarracino** [comment]
Yes, you can. Indeed, with the human genome we work just as you suggested, breaking down the problem for each chromosome.

**Comment by anna176577** [comment]
Thank you! Usually we just merge sub-files for each chromosome for any other analysis. So, how do we merge the output here or at what step in the analysis. Can you please refer me to a source to look at for an example?

**Comment by AndreaGuarracino** [comment]
We don't have a complete example yet, but we will soon have one for the human genome. You can stay up to date by looking at this repository: https://github.com/pangenome/HPRCy1.

To date, you will find instructions on how we split the input across different chromosomes.  We are running `pggb` on each chromosome on different machines, obtaining pangenomes for each chromosome.

**Comment by anna176577** [comment]
Thank you @AndreaGuarracino! I have a question regarding the input reference sequences and assemblies used in this analysis. Unlike in pggb command line, I see that there are these two types of input files. I only have two fasta files to make a graph genome. I am a little confused about the input files. Can you please explain a little about the input files as I could not find any reference?

I am using:
```
zcat input_1.fasta.gz input_2.fasta.gz > input_1+input_2.pan.fa && samtools faidx input_1+input_2.pan.fa
grep 'input_1+input_2.pan.fa' | cut -f 1-2 -d . | sort -V | uniq >haps.list
ref=input_1+input_2.pan.fa
for hap in $(cat haps.list);
do
    in=$hap.fa.gz
    out=$hap.vs.ref.paf
    sbatch -p lowmem -c 16 --wrap "wfmash -t 16 -m -N -p 90 $ref $in >$out" >>slurm.jobids
done
```

**Comment by ekg** [comment]
This particular command is designed to partition the pangenome input across scaffolded chromosomes.

For only two genomes, it is not necessary. I would just concatenate the full input set and give it as input to pggb.

**Comment by anna176577** [comment]
Thank you @ekg! I have ten fasta files in total. I am just optimizing this step for now. Earlier, I concatenated two genomes for pggb but it complaints of memory. So, I think it is my best option to partition the genomes across chromosomes. That's why I wanted to make the above command work to partition the input genome.

**Comment by anna176577** [comment]
Hello,

I tried this command line and got an error:
`pggb -i input.fasta.gz -s 5000 -p 80 -a 70 -n 5 -I 0.7 -R 0.4 -t 16 -v -L -o out`

Error:
```
[smoothxg::create_consensus_graph] final graph length 90794bp in 5 nodes
smoothxg -t 1 -g out/output.seqwish.gfa -w 10000 -M -J 0.7 -K -I 0.7 -R 0.4 -j 5000 -e 5000 -l 10000 -m out/output.smooth.maf -s out/output.consensus -a -C 10,100,1000,10000 -o out/output.smooth.gfa
2.08s user 0.72s system 83% cpu 3.37s total 128172Kb max memory
/usr/bin/time: cannot run odgi: No such file or directory
odgi build -t 1 -p -g out/output.smooth.gfa -o out/output.smooth.og
0.00s user 0.00s system 26% cpu 0.00s total 360Kb max memory
```

Thank you for the help

**Comment by ekg** [comment]
You'll need to make sure that odgi is installed in your PATH. The error
says it can't find the executable.

**Comment by anna176577** [comment]
Thank you! It worked without an error. I tried to visualize the output graphs but I am not sure what is the best way to do so. Can you please help? Thank you!

**Comment by ekg** [comment]
odgi viz provides an interface to view them. Look at the way it's called in
the pggb script.

We should provide a tutorial on this.

The consensus graphs (if you made them) are also useful. You can view them
in Bandage.

**Comment by anna176577** [comment]
Thank you! I was able to visualize the graph genome. Is there any documentation to interpret it? I also tried to generate a multiqc report using -m in the pggb command line. It generated the html report but it is not including consensus graphs or anything in the report. It just shows the the graph genome only in the report. However, I got the consensus graphs and other output files made. I am not sure if there is another way to make multiqc include those files in the report. Thank you!

**Comment by subwaystation** [comment]
Hi Anna,

there was a bug in MultiQC which I fixed in https://github.com/pangenome/pggb/pull/59. Now you should be able to see all the stats again. Thanks for reporting this!
Please checkout the latest MultiQC versionwhich can handle the `odgi stats` files: https://github.com/Imipenem/MultiQC/tree/module/odgi_stats. I updated it in the Dockerfile, too.
I added some documentation about how to interpret the visualizations in 1D and in 2D https://github.com/pangenome/pggb#general-usage. I hope this clarifies things.

Hmm, this sounds strange. Do you think you can share the data you generated the PNG from? Or the PNG itself?

Best,
Simon

**Comment by anna176577** [comment]
@subwaystation, thank you! It helped.

For the 2D PNG, I figured it creates the graph but doe not open it well. I tried downloading and opening by different ways. Can you suggest the best way to open this PNG graph in linux or other software. Thank you!

**Comment by AndreaGuarracino** [comment]
Hi @anna176577, on Linux [GIMP](https://www.gimp.org/) usually works well for opening the PNG outputs. Enjoy the graphs!
