### ISSUE TITLE
Error with latest PGGB docker build

### ISSUE THREAD

**Issue by brettChapman** [pangenome/pggb#53]
Hi

I see you've just updated the docker build. I've tried it out and noticed that I get errors with the parameters now:

```
pggb -i barley_chromosome_7H.fasta -s 100000 -p 85 -a 85 -n 18 -t 16 -m -v -l -S -o barley_pangenome_7H
Argument 'N' received invalid value type '-S'
  edyeet [target] [queries...] {OPTIONS}

    edyeet: base-accurate alignments using edlib and mashmap2

  OPTIONS:

Command terminated by signal 4
edyeet -X -s 100000 -l -S -p 85 -n 18 -a 85 -k 16 -t 16 barley_chromosome_7H.fasta barley_chromosome_7H.fasta
0.00s user 0.02s system 10% cpu 0.27s total 4492Kb max memory
```

I've also tried running with parameters the same as mentioned in issue https://github.com/pangenome/pggb/issues/51

```
pggb -i barley_chromosome_7H.fasta -s 100000 -p 85 -a 85 -n 18 -t 16 -v -L -o out_test_file

Command terminated by signal 4
edyeet -X -s 100000 -l 300000 -p 85 -n 18 -a 85 -k 16 -t 16 barley_chromosome_7H.fasta barley_chromosome_7H.fasta
0.00s user 0.03s system 18% cpu 0.19s total 4908Kb max memory
```

The error seems to happen as soon as edyeet is run. I also tried running by accessing edyeet directly, and I get an error:
```
singularity exec --bind ${PWD}:${PWD} /data/pggb_builds/pggb.sif edyeet
Illegal instruction (core dumped)
```

**Comment by brettChapman** [comment]
I just realized my original command has -l instead of -L. Rerunning with the amended command doesn't help either:

```
singularity exec --bind ${PWD}:${PWD} /data/pggb_builds/pggb.sif pggb -i barley_chromosome_7H.fasta -s 100000 -p 85 -a 85 -n 18 -t 16 -m -v -L -S -o barley_pangenome_7H
Command terminated by signal 4
edyeet -X -s 100000 -l 300000 -p 85 -n 18 -a 85 -k 16 -t 16 barley_chromosome_7H.fasta barley_chromosome_7H.fasta
0.00s user 0.03s system 19% cpu 0.21s total 4952Kb max memory
```

I'm going to try with my own build from the Dockerfile and see if it works. Will update later.

**Comment by brettChapman** [comment]
Yep, if I build the image from the Dockerfile instead of pulling from ghcr.io/pangenome/pggb it works fine and edyeet starts running. I can now also run edyeet directly from the image which didn't work before.

**Comment by AndreaGuarracino** [comment]
Hi @brettChapman, thank you for pointing this out. There was a compilation problem with the aligners. Could you please try again with the latest build available on [ghcr.io/pangenome/pggb](https://github.com/orgs/pangenome/packages/container/package/pggb)?

**Comment by brettChapman** [comment]
Thanks. It works now and starts running edyeet with no problems.

**Comment by AndreaGuarracino** [comment]
Glad to read it, you are welcome. So keep taking pggb to its limits!
