### ISSUE TITLE
Consensus paths in smoothed graph

### ISSUE THREAD

**Issue by brettChapman** [pangenome/pggb#76]
Hi

I've noticed in my smoothed graph I have over 1 million consensus paths for each of the chromosomes. For visualisation purposes in sequenceTubeMap this becomes quite a problem, having to search through all the consensus paths to find paths relating to embedded gene paths that I've added from a GFF or particular genomes of interest. I'd like to request a parameter be added to PGGB to avoid including consensus paths in the resulting smoothed graph. The consensus paths are useful, but to visualise through tools such as sequenceTubeMap it becomes a problem. My aim is to deploy sequenceTubeMap for other non-technical people to use, and I think the consensus paths will only confuse them if they are left in the final graph. Thanks.

**Comment by brettChapman** [comment]
If implementing this isn't easy (I haven't seen any parameters in the latest smoothxg which avoids including the consensus in the smoothed graph), is there a way to remove consensus paths when constructing a VG graph, prior to visualisation in sequenceTubeMap? Thanks.

**Comment by ekg** [comment]
Yes you can either use vg paths, odgi extract, or just grep -b Consensus on
your output graph.

Another way to bring down the count is to use a bigger window size in
smoothxg. (-w parameter to pggb). I've been testing 200k-500k for that.

**Comment by brettChapman** [comment]
Hi Erik

Thanks for the feedback. I've tried with a small test graph to remove the consensus and index with VG for visualisation in sequenceTubeMap, but each time the resulting graph either displays no paths in sequenceTubeMap, doesn't remove the consensus paths or running with vg paths or indexing the filtered graph ends up in an error.

I first tried:
```
grep -vb Consensus test_graph.gfa
```
This resulted in a graph which had no paths when viewed in sequenceTubeMap. I'm currently running the latest sequenceTubeMap, which I find now works with the latest VG. Using yarn to get it running works with no problems.

vg paths (vg version 1.31), depending on which parameter I used, either vg paths -r (retain only these paths), -d (drop selected paths) or -V (output only a path-graph), along with -p (my list of paths), keeps outputting errors:
```
singularity exec --bind ${PWD}:${PWD} /data/vg_builds/vg.sif vg paths -x test_graph.xg -p consensus_paths.txt -d > test_graph.noConsensus.vg
ERROR: Signal 11 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_d2HFM2/stacktrace.txt
Please include the stack trace file in your bug report!
```
Or if it worked with one of the parameter options (using -p and working only with the .vg graph instead of .pg), indexing ended up failing:
```
singularity exec --bind ${PWD}:${PWD} /data/vg_builds/vg.sif vg index test_graph.noConsensus.vg -x test_graph.noConsensus.xg
vg: src/io/load_proto_to_graph.cpp:239: vg::io::load_proto_to_graph(vg::MutablePathMutableHandleGraph*, const std::function<void(const std::function<void(vg::Graph&)>&)>&)::<lambda(vg::Graph&)>: Assertion `get_handle(m.position().node_id(), m.position().is_reverse(), visited)' failed.
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_Coov9U/stacktrace.txt
Please include the stack trace file in your bug report!
```

I looked at odgi extract, but it isn't clear how to use it. It looks like I need to supply a list of node ids, and not paths.

I've attached the test graph I'm experimenting with. It has a single 'Consensus_0' path among the chromosome paths. Thanks.


[test_graph.gfa.zip](https://github.com/pangenome/pggb/files/6202050/test_graph.gfa.zip)

**Comment by brettChapman** [comment]
Interestingly the filtered .vg and original .vg are different sizes, but the original .xg and filtered .xg are the same size:

```
-rw-rw-r-- 1 ubuntu ubuntu  85K Mar 25 04:12 test_graph.xg
-rw-rw-r-- 1 ubuntu ubuntu  93K Mar 25 04:49 test_graph.gfa
-rw-rw-r-- 1 ubuntu ubuntu 185K Mar 25 04:50 test_graph.vg
-rw-rw-r-- 1 ubuntu ubuntu 133K Mar 25 04:50 test_graph.noConsensus.vg
-rw-rw-r-- 1 ubuntu ubuntu  85K Mar 25 04:50 test_graph.noConsensus.xg
```

I tried converting the .vg back to .gfa, to see if I could get around the error and create a gfa with no consensus, but I get an error:
```
singularity exec --bind ${PWD}:${PWD} /data/vg_builds/vg.sif vg view -Vg test_graph.noConsensus.vg > test_graph.noConsensus.gfa
terminate called after throwing an instance of 'std::runtime_error'
  what():  [io::ProtobufIterator] could not parse message
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_OAvBxv/stacktrace.txt
Please include the stack trace file in your bug report!
```

**Comment by brettChapman** [comment]
I've managed to get it working eventually. After a lot of testing the only method I found which worked was this one:

```
singularity exec --bind ${PWD}:${PWD} /data/vg_builds/vg.sif vg convert -g test_graph.gfa -p > test_graph.pg
singularity exec --bind ${PWD}:${PWD} /data/vg_builds/vg.sif vg index test_graph.pg -x test_graph.xg
singularity exec --bind ${PWD}:${PWD} /data/vg_builds/vg.sif vg paths -x test_graph.xg -L | grep Consensus > consensus_paths.txt
singularity exec --bind ${PWD}:${PWD} /data/vg_builds/vg.sif vg paths -v test_graph.pg -p consensus_paths.txt -d > test_graph.noConsensus.vg
singularity exec --bind ${PWD}:${PWD} /data/vg_builds/vg.sif vg index test_graph.noConsensus.vg -x test_graph.noConsensus.xg
```

**Comment by subwaystation** [comment]
Great! Thanks for letting us know.
