### ISSUE TITLE
Segmentation fault (core dumped) when smoothing

### ISSUE THREAD

**Issue by xiaoluo91** [pangenome/pggb#77]
Hi, I ran pggb on small dataset (say 200 or 2000 virus genomes) successfully. However, when I ran it on 20000  virus genomes, it terminated at the smoothing stage. here is the information: 

`[smoothxg::main] loading graph
[smoothxg::main] prepping graph for smoothing
Command terminated by signal 11
smoothxg -t 40 -g input.fasta.pggb-s3000-p70-n10-a70-K16-k8-w10000-j5000-e5000.seqwish.gfa -w 10000 -j 5000 -e 5000 -l 10000 -m input.fasta.pggb-s3000-p70-n10-a70-K16-k8-w10000-j5000-e5000.smooth.maf -s input.fasta.pggb-s3000-p70-n10-a70-K16-k8-w10000-j5000-e5000.consensus -a -C 10,100,1000,10000
0.02s user 0.00s system 5% cpu 0.46s total 6000Kb max memory`

Here is the command I used `pggb -i input.fasta -s 3000  -p 70 -a 70 -n 10 -t 40 -v -l`

What could be the reason for this termination? Many thanks in advance.

**Comment by AndreaGuarracino** [comment]
Hi @xiaoluo91, could you please update your `pggb` installation and try again? Looking at your filenames, you are using an old version.

**Comment by subwaystation** [comment]
@xiaoluo91 Did you manage to get it to run with the current master?

**Comment by xiaoluo91** [comment]
sorry for the delay. It works, thanks for your suggestion.
