### ISSUE TITLE
/usr/bin/time: cannot run edyeet: No such file or directory

### ISSUE THREAD

**Issue by cmonat** [pangenome/pggb#83]
Hello,

I'm trying to use pggb with this command line:
`/SD5/people/s1060627/pggb/pggb -i /SD5/people/u464891/Data/Projects/mutate_fasta_genome/genome_comparison/datasets/Oryza_sativa__japonica_v3.fas -s 5000 -n 10 -p 90`
but I've got the following error message:

````bash
/usr/bin/time: cannot run edyeet: No such file or directory
edyeet -X -s 5000 -l 15000 -p 90 -n 10 -a 0 -k 16 -t 1 /SD5/people/u464891/Data/Projects/mutate_fasta_genome/genome_comparison/datasets/Oryza_sativa__japonica_v3.fas /SD5/people/u464891/Data/Projects/mutate_fasta_genome/genome_comparison/datasets/Oryza_sativa__japonica_v3.fas
0.00s user 0.00s system 0% cpu 0.00s total 352Kb max memory
````

Does it exist a way to specify the path of edyeet so pggb can find it, cause it seems to be the problem for what I understood from the error message?

Thanks in advance for your help
Have a great day
Best,
C.

**Comment by subwaystation** [comment]
Edyeet is no longer part of PGGB.
